unit hiChildPanel_25382C0;

interface

uses 
  Windows,
  hiEditMulti,
  hiPanel,
  hiEdit,
  hiStrCat,
  hiButton,
  hiClipboardHook,
  hiComboBox,
  hiHub,
  hiLabel,
  hiTimer,
  hiMultiBase,
  kol,Share;

type
TClassChildPanel_25382C0 = class(TClassMultiBase)
 public
  EditMulti_245C450:THIEditMulti;
  Panel_24C7C90:THIPanel;
  Edit_24C8050:THIEdit;
  Edit_24C80F0:THIEdit;
  StrCat_24BEA48:THIStrCat;
  Button_24C82D0:THIButton;
  Button_24C8370:THIButton;
  Edit_24C8410:THIEdit;
  StrCat_24BE9B0:THIStrCat;
  Edit_24C84B0:THIEdit;
  Button_24C8550:THIButton;
  StrCat_24BEB78:THIStrCat;
  Edit_24C85F0:THIEdit;
  Button_24C8690:THIButton;
  Button_24C87D0:THIButton;
  Button_24C8870:THIButton;
  Button_24C8910:THIButton;
  Edit_24C89B0:THIEdit;
  StrCat_24BECA8:THIStrCat;
  StrCat_24BED40:THIStrCat;
  StrCat_24BEDD8:THIStrCat;
  Edit_24C8A50:THIEdit;
  Edit_24C8AF0:THIEdit;
  ClipboardHook_24BEE70:THIClipboardHook;
  Edit_24C8C30:THIEdit;
  ComboBox_24C9130:THIComboBox;
  StrCat_24BEF08:THIStrCat;
  Edit_24C9270:THIEdit;
  Edit_24C98B0:THIEdit;
  Button_24C99F0:THIButton;
  Edit_24C9A90:THIEdit;
  Button_24C9B30:THIButton;
  Button_24C9BD0:THIButton;
  StrCat_24BEFA0:THIStrCat;
  StrCat_24BF0D0:THIStrCat;
  Edit_24C8730:THIEdit;
  Edit_24C9C70:THIEdit;
  Edit_24C9D10:THIEdit;
  StrCat_24BF200:THIStrCat;
  Hub_25384D0:THIHub;
  Edit_24C9DB0:THIEdit;
  StrCat_24BF330:THIStrCat;
  Label_24CA0D0:THILabel;
  Label_24CA170:THILabel;
  Label_24CA210:THILabel;
  Edit_24CA2B0:THIEdit;
  Button_24CA350:THIButton;
  StrCat_24BF4F8:THIStrCat;
  Hub_2538210:THIHub;
  StrCat_24BF460:THIStrCat;
  Edit_24CA3F0:THIEdit;
  Button_24CA490:THIButton;
  Hub_2538370:THIHub;
  Button_24CA530:THIButton;
  Button_24CA5D0:THIButton;
  Button_24CA670:THIButton;
  Button_24CA710:THIButton;
  Label_24CA7B0:THILabel;
  Edit_24CA850:THIEdit;
  Edit_24CA8F0:THIEdit;
  StrCat_24BF9B8:THIStrCat;
  StrCat_24BFA50:THIStrCat;
  Edit_24CA990:THIEdit;
  Edit_24CAA30:THIEdit;
  Hub_2538580:THIHub;
  Hub_2538420:THIHub;
  StrCat_24BFB80:THIStrCat;
  Edit_24CAAD0:THIEdit;
  StrCat_24BFCB0:THIStrCat;
  Label_24CAB70:THILabel;
  Label_24CAC10:THILabel;
  Label_24CACB0:THILabel;
  Edit_24CAD50:THIEdit;
  Edit_24CADF0:THIEdit;
  StrCat_24BFE78:THIStrCat;
  StrCat_24BFFA8:THIStrCat;
  Timer_24C00D8:THITimer;
  Edit_24CB250:THIEdit;
  Edit_24CB2F0:THIEdit;
  Edit_24CB390:THIEdit;

  ParentClass:TObject;

  constructor Create(_parent:pointer; _Control:PControl; _ParentClass:TObject);
  destructor Destroy; override;
 end;

  function Create_hiChildPanel_25382C0(_parent:pointer; Control:PControl; _ParentClass:TObject):THiEditMulti;

implementation


function Create_hiChildPanel_25382C0;
begin
  Result := THiEditMulti(TClassChildPanel_25382C0.Create(_parent, Control, _ParentClass).Child);
end;

constructor TClassChildPanel_25382C0.Create;
begin
  inherited;
  ParentClass := _ParentClass;
 //Panel_24C7C90 - Main
  Panel_24C7C90 := THIPanel.Create(_Control);
  with Panel_24C7C90 do begin
    ManFlags := 0;
    _prop_Left := 165;
    _prop_Top := 20;
    _prop_Width := 750;
    _prop_Height := 375;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar('FormHydraUb'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Caption := PChar(#0);
    _prop_BorderStyle := 0;
    _prop_BorderWidth := 1;
    _prop_BevelInner := 2;
    _prop_BevelOuter := 0;
    _prop_BevelWidth := 1;
    _prop_Alignment := 0;
    _prop_MouseCapture := False;
    Init;
  end;
//Init for EditMulti;
  EditMulti_245C450 := THIEditMulti.Create;
  with EditMulti_245C450 do begin
    SetLength(Works,1);
    SetLength(Vars, 0);
  end;
//Init for Edit;
  Edit_24C8050 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C8050 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24C80F0 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C80F0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 285;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24BEA48 := THIStrCat.Create;
  with StrCat_24BEA48 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Button;
  Button_24C82D0 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24C82D0 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 20;
    _prop_Width := 80;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('hydra'#0);
    _prop_Data := _DoData(PChar('hydra '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24C8370 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24C8370 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 120;
    _prop_Width := 80;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Записать подобранную пару логин/пароль в файл, вместо того чтоб просто вывести в stdout'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('Output *.txt'#0);
    _prop_Data := _DoData(PChar(' -o ~/result.log '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Edit;
  Edit_24C8410 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C8410 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 225;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24BE9B0 := THIStrCat.Create;
  with StrCat_24BE9B0 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24C84B0 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C84B0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 305;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_24C8550 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24C8550 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 145;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Прекратить работу, как только первая пара логин:пароль будет подобрана, только для текущего хоста.'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-f'#0);
    _prop_Data := _DoData(PChar('-f '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for StrCat;
  StrCat_24BEB78 := THIStrCat.Create;
  with StrCat_24BEB78 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24C85F0 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C85F0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_24C8690 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24C8690 do begin
    ManFlags := 0;
    _prop_Left := 325;
    _prop_Top := 81;
    _prop_Width := 75;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Использовать список логинов и паролей из указанных файлов'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('login + pass'#0);
    _prop_Data := _DoData(PChar('-L ~/login.txt -P ~/pass.txt '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24C87D0 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24C87D0 do begin
    ManFlags := 0;
    _prop_Left := 100;
    _prop_Top := 145;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Прекратить работу, как только первая пара логин:пароль будет подобрана, глобально.'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-F'#0);
    _prop_Data := _DoData(PChar('-F '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24C8870 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24C8870 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 170;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Более подробный вывод информации о процессе '#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-v'#0);
    _prop_Data := _DoData(PChar('-v '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24C8910 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24C8910 do begin
    ManFlags := 0;
    _prop_Left := 100;
    _prop_Top := 170;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Выводить каждый подбираемый логин + пароль '#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-V'#0);
    _prop_Data := _DoData(PChar('-V '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Edit;
  Edit_24C89B0 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C89B0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 265;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24BECA8 := THIStrCat.Create;
  with StrCat_24BECA8 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24BED40 := THIStrCat.Create;
  with StrCat_24BED40 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24BEDD8 := THIStrCat.Create;
  with StrCat_24BEDD8 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24C8A50 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C8A50 do begin
    ManFlags := 0;
    _prop_Left := 215;
    _prop_Top := 20;
    _prop_Width := 460;
    _prop_Height := 25;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24C8AF0 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C8AF0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 325;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for ClipboardHook;
  ClipboardHook_24BEE70 := THIClipboardHook.Create(Panel_24C7C90.Control);
  with ClipboardHook_24BEE70 do begin
    _prop_DataStream := 1;
    _prop_NextHook := 0;
  end;
//Init for Edit;
  Edit_24C8C30 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C8C30 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for ComboBox;
  ComboBox_24C9130 := THIComboBox.Create(Panel_24C7C90.Control);
  with ComboBox_24C9130 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 220;
    _prop_Width := 75;
    _prop_Height := 21;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Сервис'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_FileName := PChar(#0);
    _prop_Strings := PChar(' http-get'#13#10' ssh'#13#10' ftp'#0);
    _prop_AddType := 0;
    _prop_Text := PChar('ComboBox'#0);
    _prop_DataType := 1;
    _prop_ReadOnly := 0;
    _prop_Sort := False;
    _prop_ItemHeight := 20;
    Init;
  end;
//Init for StrCat;
  StrCat_24BEF08 := THIStrCat.Create;
  with StrCat_24BEF08 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24C9270 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C9270 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 245;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24C98B0 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C98B0 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 195;
    _prop_Width := 90;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('ip'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_24C99F0 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24C99F0 do begin
    ManFlags := 0;
    _prop_Left := 270;
    _prop_Top := 195;
    _prop_Width := 40;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Файл со списком целей для брутфорса (можно с указанием порта через двоеточие), по одному на строку.'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('IP-list'#0);
    _prop_Data := _DoData(PChar('-M ~/iplist.txt '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Edit;
  Edit_24C9A90 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C9A90 do begin
    ManFlags := 0;
    _prop_Left := 170;
    _prop_Top := 195;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Указание порта (отличного от дефолтного) сервиса'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('Port'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := False;
    Init;
  end;
//Init for Button;
  Button_24C9B30 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24C9B30 do begin
    ManFlags := 0;
    _prop_Left := 140;
    _prop_Top := 195;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('IP'#0);
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24C9BD0 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24C9BD0 do begin
    ManFlags := 0;
    _prop_Left := 220;
    _prop_Top := 195;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Указание порта (отличного от дефолтного) сервиса'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('Port'#0);
    _prop_Data := _DoData(PChar(' -s '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for StrCat;
  StrCat_24BEFA0 := THIStrCat.Create;
  with StrCat_24BEFA0 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24BF0D0 := THIStrCat.Create;
  with StrCat_24BF0D0 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24C8730 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C8730 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24C9C70 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C9C70 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 185;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24C9D10 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C9D10 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24BF200 := THIStrCat.Create;
  with StrCat_24BF200 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Hub;
  Hub_25384D0 := THIHub.Create;
  with Hub_25384D0 do begin
    _prop_InCount := 1;
    _prop_OutCount := 2;
  end;
//Init for Edit;
  Edit_24C9DB0 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24C9DB0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 345;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24BF330 := THIStrCat.Create;
  with StrCat_24BF330 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Label;
  Label_24CA0D0 := THILabel.Create(Panel_24C7C90.Control);
  with Label_24CA0D0 do begin
    ManFlags := 0;
    _prop_Left := 81;
    _prop_Top := 145;
    _prop_Width := 20;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',12,1,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Transparent := False;
    _prop_Caption := PChar('or'#0);
    _prop_AutoSize := True;
    _prop_Alignment := taLeft;
    _prop_ColorHover := 0;
    _prop_Underline := False;
    Init;
  end;
//Init for Label;
  Label_24CA170 := THILabel.Create(Panel_24C7C90.Control);
  with Label_24CA170 do begin
    ManFlags := 0;
    _prop_Left := 81;
    _prop_Top := 170;
    _prop_Width := 20;
    _prop_Height := 24;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',12,1,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Transparent := False;
    _prop_Caption := PChar('or'#0);
    _prop_AutoSize := True;
    _prop_Alignment := taLeft;
    _prop_ColorHover := 0;
    _prop_Underline := False;
    Init;
  end;
//Init for Label;
  Label_24CA210 := THILabel.Create(Panel_24C7C90.Control);
  with Label_24CA210 do begin
    ManFlags := 0;
    _prop_Left := 251;
    _prop_Top := 193;
    _prop_Width := 20;
    _prop_Height := 24;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',12,1,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Transparent := False;
    _prop_Caption := PChar('or'#0);
    _prop_AutoSize := True;
    _prop_Alignment := taLeft;
    _prop_ColorHover := 0;
    _prop_Underline := False;
    Init;
  end;
//Init for Edit;
  Edit_24CA2B0 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24CA2B0 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 245;
    _prop_Width := 220;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Путь, который закрыт для нас запросом пары логин:пароль /example/'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('/example/'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_24CA350 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24CA350 do begin
    ManFlags := 0;
    _prop_Left := 270;
    _prop_Top := 245;
    _prop_Width := 40;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Путь, который закрыт для нас запросом пары логин:пароль /example/'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('Paste'#0);
    _prop_Data := _DoData(PChar(' '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for StrCat;
  StrCat_24BF4F8 := THIStrCat.Create;
  with StrCat_24BF4F8 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Hub;
  Hub_2538210 := THIHub.Create;
  with Hub_2538210 do begin
    _prop_InCount := 1;
    _prop_OutCount := 2;
  end;
//Init for StrCat;
  StrCat_24BF460 := THIStrCat.Create;
  with StrCat_24BF460 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24CA3F0 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24CA3F0 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_24CA490 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24CA490 do begin
    ManFlags := 0;
    _prop_Left := 680;
    _prop_Top := 20;
    _prop_Width := 55;
    _prop_Height := 25;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('COPY'#0);
    _prop_Data := _DoData(PChar('Код скопирован в буфер обмена!'#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Hub;
  Hub_2538370 := THIHub.Create;
  with Hub_2538370 do begin
    _prop_InCount := 1;
    _prop_OutCount := 2;
  end;
//Init for Button;
  Button_24CA530 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24CA530 do begin
    ManFlags := 0;
    _prop_Left := 160;
    _prop_Top := 70;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Использовать указанный логин для попытки аутентификации'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('Paste'#0);
    _prop_Data := _DoData(PChar('-l '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24CA5D0 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24CA5D0 do begin
    ManFlags := 0;
    _prop_Left := 160;
    _prop_Top := 95;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Использовать указанный пароль для попытки аутентификации'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('Paste'#0);
    _prop_Data := _DoData(PChar(' -p '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24CA670 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24CA670 do begin
    ManFlags := 0;
    _prop_Left := 235;
    _prop_Top := 70;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Использовать список логинов из указанного файла'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('login-file'#0);
    _prop_Data := _DoData(PChar(' -L ~/login.txt '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24CA710 := THIButton.Create(Panel_24C7C90.Control);
  with Button_24CA710 do begin
    ManFlags := 0;
    _prop_Left := 235;
    _prop_Top := 95;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Использовать список паролей из указанного файла'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('pass file'#0);
    _prop_Data := _DoData(PChar(' -P ~/pass.txt '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Label;
  Label_24CA7B0 := THILabel.Create(Panel_24C7C90.Control);
  with Label_24CA7B0 do begin
    ManFlags := 0;
    _prop_Left := 305;
    _prop_Top := 81;
    _prop_Width := 20;
    _prop_Height := 24;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',12,1,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Transparent := False;
    _prop_Caption := PChar('or'#0);
    _prop_AutoSize := True;
    _prop_Alignment := taLeft;
    _prop_ColorHover := 0;
    _prop_Underline := False;
    Init;
  end;
//Init for Edit;
  Edit_24CA850 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24CA850 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 95;
    _prop_Width := 110;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Использовать указанный пароль для попытки аутентификации'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('password'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CA8F0 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24CA8F0 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 70;
    _prop_Width := 110;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Использовать указанный логин для попытки аутентификации'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('login'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24BF9B8 := THIStrCat.Create;
  with StrCat_24BF9B8 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24BFA50 := THIStrCat.Create;
  with StrCat_24BFA50 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24CA990 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24CA990 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CAA30 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24CAA30 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Hub;
  Hub_2538580 := THIHub.Create;
  with Hub_2538580 do begin
    _prop_InCount := 1;
    _prop_OutCount := 2;
  end;
//Init for Hub;
  Hub_2538420 := THIHub.Create;
  with Hub_2538420 do begin
    _prop_InCount := 1;
    _prop_OutCount := 2;
  end;
//Init for StrCat;
  StrCat_24BFB80 := THIStrCat.Create;
  with StrCat_24BFB80 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24CAAD0 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24CAAD0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24BFCB0 := THIStrCat.Create;
  with StrCat_24BFCB0 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Label;
  Label_24CAB70 := THILabel.Create(Panel_24C7C90.Control);
  with Label_24CAB70 do begin
    ManFlags := 0;
    _prop_Left := 216;
    _prop_Top := 70;
    _prop_Width := 20;
    _prop_Height := 24;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',12,1,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Transparent := False;
    _prop_Caption := PChar('or'#0);
    _prop_AutoSize := True;
    _prop_Alignment := taLeft;
    _prop_ColorHover := 0;
    _prop_Underline := False;
    Init;
  end;
//Init for Label;
  Label_24CAC10 := THILabel.Create(Panel_24C7C90.Control);
  with Label_24CAC10 do begin
    ManFlags := 0;
    _prop_Left := 216;
    _prop_Top := 95;
    _prop_Width := 20;
    _prop_Height := 24;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',12,1,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Transparent := False;
    _prop_Caption := PChar('or'#0);
    _prop_AutoSize := True;
    _prop_Alignment := taLeft;
    _prop_ColorHover := 0;
    _prop_Underline := False;
    Init;
  end;
//Init for Label;
  Label_24CACB0 := THILabel.Create(Panel_24C7C90.Control);
  with Label_24CACB0 do begin
    ManFlags := 0;
    _prop_Left := 290;
    _prop_Top := 75;
    _prop_Width := 16;
    _prop_Height := 41;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',26,1,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Transparent := False;
    _prop_Caption := PChar('}'#0);
    _prop_AutoSize := True;
    _prop_Alignment := taLeft;
    _prop_ColorHover := 0;
    _prop_Underline := False;
    Init;
  end;
//Init for Edit;
  Edit_24CAD50 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24CAD50 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CADF0 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24CADF0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24BFE78 := THIStrCat.Create;
  with StrCat_24BFE78 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24BFFA8 := THIStrCat.Create;
  with StrCat_24BFFA8 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Timer;
  Timer_24C00D8 := THITimer.Create;
  with Timer_24C00D8 do begin
    _prop_Interval := 3000;
    _prop_Enable := False;
    _prop_AutoStop := 1;
    _prop_OverCall := 0;
  end;
//Init for Edit;
  Edit_24CB250 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24CB250 do begin
    ManFlags := 0;
    _prop_Left := 1315;
    _prop_Top := 370;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(' '#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CB2F0 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24CB2F0 do begin
    ManFlags := 0;
    _prop_Left := 1285;
    _prop_Top := 305;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',10,0,255,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('Код скопирован в буфер обмена!'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CB390 := THIEdit.Create(Panel_24C7C90.Control);
  with Edit_24CB390 do begin
    ManFlags := 0;
    _prop_Left := 475;
    _prop_Top := 50;
    _prop_Width := 260;
    _prop_Height := 25;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',10,1,255,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := True;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
  Child := EditMulti_245C450;
  EditMulti_245C450.MainClass := Self;
  EditMulti_245C450.Parent := _parent;
 //Make all connection in scheme
  EditMulti_245C450.Works[0]               := _DoEvent(Panel_24C7C90._work_doVisible,1);
  Edit_24C8050._event_onChange             := _DoEvent(Edit_24CA990._work_doText,0);
  Edit_24C80F0._event_onChange             := _DoEvent(Edit_24C89B0._work_doText,0);
  StrCat_24BEA48._event_onStrCat           := _DoEvent(Edit_24C84B0._work_doText,0);
  StrCat_24BEA48._data_Str1                := _DoEvent(Edit_24C8410._var_Text,0);
  Button_24C82D0._event_onClick            := _DoEvent(Edit_24C8050._work_doText,0);
  Button_24C8370._event_onClick            := _DoEvent(StrCat_24BE9B0._work_doStrCat,0);
  Edit_24C8410._event_onChange             := _DoEvent(Edit_24C84B0._work_doText,0);
  StrCat_24BE9B0._event_onStrCat           := _DoEvent(Edit_24C85F0._work_doText,0);
  StrCat_24BE9B0._data_Str1                := _DoEvent(Edit_24C84B0._var_Text,0);
  Edit_24C84B0._event_onChange             := _DoEvent(Edit_24C85F0._work_doText,0);
  Button_24C8550._event_onClick            := _DoEvent(StrCat_24BEB78._work_doStrCat,0);
  StrCat_24BEB78._event_onStrCat           := _DoEvent(Edit_24C80F0._work_doText,0);
  StrCat_24BEB78._data_Str1                := _DoEvent(Edit_24C85F0._var_Text,0);
  Edit_24C85F0._event_onChange             := _DoEvent(Edit_24C80F0._work_doText,0);
  Button_24C8690._event_onClick            := _DoEvent(StrCat_24BEA48._work_doStrCat,0);
  Button_24C87D0._event_onClick            := _DoEvent(StrCat_24BECA8._work_doStrCat,0);
  Button_24C8870._event_onClick            := _DoEvent(StrCat_24BED40._work_doStrCat,0);
  Button_24C8910._event_onClick            := _DoEvent(StrCat_24BEDD8._work_doStrCat,0);
  Edit_24C89B0._event_onChange             := _DoEvent(Edit_24C8AF0._work_doText,0);
  StrCat_24BECA8._event_onStrCat           := _DoEvent(Edit_24C89B0._work_doText,0);
  StrCat_24BECA8._data_Str1                := _DoEvent(Edit_24C80F0._var_Text,0);
  StrCat_24BED40._event_onStrCat           := _DoEvent(Edit_24C8AF0._work_doText,0);
  StrCat_24BED40._data_Str1                := _DoEvent(Edit_24C89B0._var_Text,0);
  StrCat_24BEDD8._event_onStrCat           := _DoEvent(Edit_24C9DB0._work_doText,0);
  StrCat_24BEDD8._data_Str1                := _DoEvent(Edit_24C8AF0._var_Text,0);
  Edit_24C8AF0._event_onChange             := _DoEvent(Edit_24C9DB0._work_doText,0);
  ClipboardHook_24BEE70._data_Text         := _DoEvent(Edit_24C8A50._var_Text,0);
  Edit_24C8C30._event_onChange             := _DoEvent(Edit_24C9270._work_doText,0);
  ComboBox_24C9130._event_onClick          := _DoEvent(StrCat_24BEF08._work_doStrCat,0);
  StrCat_24BEF08._event_onStrCat           := _DoEvent(Edit_24C9D10._work_doText,0);
  StrCat_24BEF08._data_Str1                := _DoEvent(Edit_24CA3F0._var_Text,0);
  Edit_24C9270._event_onChange             := _DoEvent(Edit_24C8730._work_doText,0);
  Button_24C99F0._event_onClick            := _DoEvent(StrCat_24BF330._work_doStrCat,0);
  Button_24C9B30._event_onClick            := _DoEvent(StrCat_24BEFA0._work_doStrCat,0);
  Button_24C9BD0._event_onClick            := _DoEvent(Hub_25384D0.doEvent,0);
  StrCat_24BEFA0._event_onStrCat           := _DoEvent(Edit_24C9270._work_doText,0);
  StrCat_24BEFA0._data_Str1                := _DoEvent(Edit_24C8C30._var_Text,0);
  StrCat_24BEFA0._data_Str2                := _DoEvent(Edit_24C98B0._var_Text,0);
  StrCat_24BF0D0._event_onStrCat           := _DoEvent(Edit_24C8730._work_doText,0);
  StrCat_24BF0D0._data_Str1                := _DoEvent(Edit_24C9270._var_Text,0);
  Edit_24C8730._event_onChange             := _DoEvent(Edit_24CA3F0._work_doText,0);
  Edit_24C9C70._event_onChange             := _DoEvent(Edit_24C8A50._work_doText,0);
  Edit_24C9D10._event_onChange             := _DoEvent(Edit_24C9C70._work_doText,0);
  StrCat_24BF200._event_onStrCat           := _DoEvent(Edit_24CA3F0._work_doText,0);
  StrCat_24BF200._data_Str1                := _DoEvent(Edit_24C8730._var_Text,0);
  StrCat_24BF200._data_Str2                := _DoEvent(Edit_24C9A90._var_Text,0);
  Hub_25384D0.onEvent[0]                   := _DoEvent(StrCat_24BF0D0._work_doStrCat,0);
  Hub_25384D0.onEvent[1]                   := _DoEvent(StrCat_24BF200._work_doStrCat,0);
  Edit_24C9DB0._event_onChange             := _DoEvent(Edit_24C8C30._work_doText,0);
  StrCat_24BF330._event_onStrCat           := _DoEvent(Edit_24C8C30._work_doText,0);
  StrCat_24BF330._data_Str1                := _DoEvent(Edit_24C9DB0._var_Text,0);
  Button_24CA350._event_onClick            := _DoEvent(Hub_2538210.doEvent,0);
  StrCat_24BF4F8._event_onStrCat           := _DoEvent(Edit_24C9C70._work_doText,0);
  StrCat_24BF4F8._data_Str1                := _DoEvent(Edit_24C9D10._var_Text,0);
  Hub_2538210.onEvent[0]                   := _DoEvent(StrCat_24BF4F8._work_doStrCat,0);
  Hub_2538210.onEvent[1]                   := _DoEvent(StrCat_24BF460._work_doStrCat,0);
  StrCat_24BF460._event_onStrCat           := _DoEvent(Edit_24C8A50._work_doText,0);
  StrCat_24BF460._data_Str1                := _DoEvent(Edit_24C9C70._var_Text,0);
  StrCat_24BF460._data_Str2                := _DoEvent(Edit_24CA2B0._var_Text,0);
  Edit_24CA3F0._event_onChange             := _DoEvent(Edit_24C9D10._work_doText,0);
  Button_24CA490._event_onClick            := _DoEvent(Hub_2538370.doEvent,0);
  Hub_2538370.onEvent[0]                   := _DoEvent(ClipboardHook_24BEE70._work_doSetText,0);
  Hub_2538370.onEvent[1]                   := _DoEvent(Edit_24CB2F0._work_doText,0);
  Button_24CA530._event_onClick            := _DoEvent(Hub_2538580.doEvent,0);
  Button_24CA5D0._event_onClick            := _DoEvent(Hub_2538420.doEvent,0);
  Button_24CA670._event_onClick            := _DoEvent(StrCat_24BFE78._work_doStrCat,0);
  Button_24CA710._event_onClick            := _DoEvent(StrCat_24BFFA8._work_doStrCat,0);
  StrCat_24BF9B8._event_onStrCat           := _DoEvent(Edit_24CAD50._work_doText,0);
  StrCat_24BF9B8._data_Str1                := _DoEvent(Edit_24CA990._var_Text,0);
  StrCat_24BF9B8._data_Str2                := _DoEvent(Edit_24CA8F0._var_Text,0);
  StrCat_24BFA50._event_onStrCat           := _DoEvent(Edit_24CA990._work_doText,0);
  StrCat_24BFA50._data_Str1                := _DoEvent(Edit_24C8050._var_Text,0);
  Edit_24CA990._event_onChange             := _DoEvent(Edit_24CAD50._work_doText,0);
  Edit_24CAA30._event_onChange             := _DoEvent(Edit_24CAAD0._work_doText,0);
  Hub_2538580.onEvent[0]                   := _DoEvent(StrCat_24BFA50._work_doStrCat,0);
  Hub_2538580.onEvent[1]                   := _DoEvent(StrCat_24BF9B8._work_doStrCat,0);
  Hub_2538420.onEvent[0]                   := _DoEvent(StrCat_24BFB80._work_doStrCat,0);
  Hub_2538420.onEvent[1]                   := _DoEvent(StrCat_24BFCB0._work_doStrCat,0);
  StrCat_24BFB80._event_onStrCat           := _DoEvent(Edit_24CAAD0._work_doText,0);
  StrCat_24BFB80._data_Str1                := _DoEvent(Edit_24CAA30._var_Text,0);
  Edit_24CAAD0._event_onChange             := _DoEvent(Edit_24C8410._work_doText,0);
  StrCat_24BFCB0._event_onStrCat           := _DoEvent(Edit_24C8410._work_doText,0);
  StrCat_24BFCB0._data_Str1                := _DoEvent(Edit_24CAAD0._var_Text,0);
  StrCat_24BFCB0._data_Str2                := _DoEvent(Edit_24CA850._var_Text,0);
  Edit_24CAD50._event_onChange             := _DoEvent(Edit_24CADF0._work_doText,0);
  Edit_24CADF0._event_onChange             := _DoEvent(Edit_24CAA30._work_doText,0);
  StrCat_24BFE78._event_onStrCat           := _DoEvent(Edit_24CADF0._work_doText,0);
  StrCat_24BFE78._data_Str1                := _DoEvent(Edit_24CAD50._var_Text,0);
  StrCat_24BFFA8._event_onStrCat           := _DoEvent(Edit_24CAA30._work_doText,0);
  StrCat_24BFFA8._data_Str1                := _DoEvent(Edit_24CADF0._var_Text,0);
  Timer_24C00D8._event_onTimer             := _DoEvent(Edit_24CB250._work_doText,0);
  Edit_24CB250._event_onChange             := _DoEvent(Edit_24CB390._work_doText,0);
  Edit_24CB2F0._event_onChange             := _DoEvent(Edit_24CB390._work_doText,0);
  Edit_24CB390._event_onChange             := _DoEvent(Timer_24C00D8._work_doTimer,0);
  Panel_24C7C90._prop_HintManager := nil;
  Panel_24C7C90._prop_Layout := nil;
  Edit_24C8050._prop_HintManager := nil;
  Edit_24C8050._prop_Layout := nil;
  Edit_24C80F0._prop_HintManager := nil;
  Edit_24C80F0._prop_Layout := nil;
  Button_24C82D0._prop_HintManager := nil;
  Button_24C82D0._prop_Layout := nil;
  Button_24C8370._prop_HintManager := nil;
  Button_24C8370._prop_Layout := nil;
  Edit_24C8410._prop_HintManager := nil;
  Edit_24C8410._prop_Layout := nil;
  Edit_24C84B0._prop_HintManager := nil;
  Edit_24C84B0._prop_Layout := nil;
  Button_24C8550._prop_HintManager := nil;
  Button_24C8550._prop_Layout := nil;
  Edit_24C85F0._prop_HintManager := nil;
  Edit_24C85F0._prop_Layout := nil;
  Button_24C8690._prop_HintManager := nil;
  Button_24C8690._prop_Layout := nil;
  Button_24C87D0._prop_HintManager := nil;
  Button_24C87D0._prop_Layout := nil;
  Button_24C8870._prop_HintManager := nil;
  Button_24C8870._prop_Layout := nil;
  Button_24C8910._prop_HintManager := nil;
  Button_24C8910._prop_Layout := nil;
  Edit_24C89B0._prop_HintManager := nil;
  Edit_24C89B0._prop_Layout := nil;
  Edit_24C8A50._prop_HintManager := nil;
  Edit_24C8A50._prop_Layout := nil;
  Edit_24C8AF0._prop_HintManager := nil;
  Edit_24C8AF0._prop_Layout := nil;
  Edit_24C8C30._prop_HintManager := nil;
  Edit_24C8C30._prop_Layout := nil;
  ComboBox_24C9130._prop_HintManager := nil;
  ComboBox_24C9130._prop_Layout := nil;
  ComboBox_24C9130._prop_IndexManager := nil;
  ComboBox_24C9130._prop_BoxDrawManager := nil;
  ComboBox_24C9130._prop_IconsManager := nil;
  Edit_24C9270._prop_HintManager := nil;
  Edit_24C9270._prop_Layout := nil;
  Edit_24C98B0._prop_HintManager := nil;
  Edit_24C98B0._prop_Layout := nil;
  Button_24C99F0._prop_HintManager := nil;
  Button_24C99F0._prop_Layout := nil;
  Edit_24C9A90._prop_HintManager := nil;
  Edit_24C9A90._prop_Layout := nil;
  Button_24C9B30._prop_HintManager := nil;
  Button_24C9B30._prop_Layout := nil;
  Button_24C9BD0._prop_HintManager := nil;
  Button_24C9BD0._prop_Layout := nil;
  Edit_24C8730._prop_HintManager := nil;
  Edit_24C8730._prop_Layout := nil;
  Edit_24C9C70._prop_HintManager := nil;
  Edit_24C9C70._prop_Layout := nil;
  Edit_24C9D10._prop_HintManager := nil;
  Edit_24C9D10._prop_Layout := nil;
  Edit_24C9DB0._prop_HintManager := nil;
  Edit_24C9DB0._prop_Layout := nil;
  Label_24CA0D0._prop_HintManager := nil;
  Label_24CA0D0._prop_Layout := nil;
  Label_24CA170._prop_HintManager := nil;
  Label_24CA170._prop_Layout := nil;
  Label_24CA210._prop_HintManager := nil;
  Label_24CA210._prop_Layout := nil;
  Edit_24CA2B0._prop_HintManager := nil;
  Edit_24CA2B0._prop_Layout := nil;
  Button_24CA350._prop_HintManager := nil;
  Button_24CA350._prop_Layout := nil;
  Edit_24CA3F0._prop_HintManager := nil;
  Edit_24CA3F0._prop_Layout := nil;
  Button_24CA490._prop_HintManager := nil;
  Button_24CA490._prop_Layout := nil;
  Button_24CA530._prop_HintManager := nil;
  Button_24CA530._prop_Layout := nil;
  Button_24CA5D0._prop_HintManager := nil;
  Button_24CA5D0._prop_Layout := nil;
  Button_24CA670._prop_HintManager := nil;
  Button_24CA670._prop_Layout := nil;
  Button_24CA710._prop_HintManager := nil;
  Button_24CA710._prop_Layout := nil;
  Label_24CA7B0._prop_HintManager := nil;
  Label_24CA7B0._prop_Layout := nil;
  Edit_24CA850._prop_HintManager := nil;
  Edit_24CA850._prop_Layout := nil;
  Edit_24CA8F0._prop_HintManager := nil;
  Edit_24CA8F0._prop_Layout := nil;
  Edit_24CA990._prop_HintManager := nil;
  Edit_24CA990._prop_Layout := nil;
  Edit_24CAA30._prop_HintManager := nil;
  Edit_24CAA30._prop_Layout := nil;
  Edit_24CAAD0._prop_HintManager := nil;
  Edit_24CAAD0._prop_Layout := nil;
  Label_24CAB70._prop_HintManager := nil;
  Label_24CAB70._prop_Layout := nil;
  Label_24CAC10._prop_HintManager := nil;
  Label_24CAC10._prop_Layout := nil;
  Label_24CACB0._prop_HintManager := nil;
  Label_24CACB0._prop_Layout := nil;
  Edit_24CAD50._prop_HintManager := nil;
  Edit_24CAD50._prop_Layout := nil;
  Edit_24CADF0._prop_HintManager := nil;
  Edit_24CADF0._prop_Layout := nil;
  Edit_24CB250._prop_HintManager := nil;
  Edit_24CB250._prop_Layout := nil;
  Edit_24CB2F0._prop_HintManager := nil;
  Edit_24CB2F0._prop_Layout := nil;
  Edit_24CB390._prop_HintManager := nil;
  Edit_24CB390._prop_Layout := nil;
  Panel_24C7C90.Control.Tabulate;

  ParentElement := Panel_24C7C90;
end;

destructor TClassChildPanel_25382C0.Destroy;
begin
  Edit_24CB390.Destroy;
  Edit_24CB2F0.Destroy;
  Edit_24CB250.Destroy;
  Timer_24C00D8.Destroy;
  StrCat_24BFFA8.Destroy;
  StrCat_24BFE78.Destroy;
  Edit_24CADF0.Destroy;
  Edit_24CAD50.Destroy;
  Label_24CACB0.Destroy;
  Label_24CAC10.Destroy;
  Label_24CAB70.Destroy;
  StrCat_24BFCB0.Destroy;
  Edit_24CAAD0.Destroy;
  StrCat_24BFB80.Destroy;
  Hub_2538420.Destroy;
  Hub_2538580.Destroy;
  Edit_24CAA30.Destroy;
  Edit_24CA990.Destroy;
  StrCat_24BFA50.Destroy;
  StrCat_24BF9B8.Destroy;
  Edit_24CA8F0.Destroy;
  Edit_24CA850.Destroy;
  Label_24CA7B0.Destroy;
  Button_24CA710.Destroy;
  Button_24CA670.Destroy;
  Button_24CA5D0.Destroy;
  Button_24CA530.Destroy;
  Hub_2538370.Destroy;
  Button_24CA490.Destroy;
  Edit_24CA3F0.Destroy;
  StrCat_24BF460.Destroy;
  Hub_2538210.Destroy;
  StrCat_24BF4F8.Destroy;
  Button_24CA350.Destroy;
  Edit_24CA2B0.Destroy;
  Label_24CA210.Destroy;
  Label_24CA170.Destroy;
  Label_24CA0D0.Destroy;
  StrCat_24BF330.Destroy;
  Edit_24C9DB0.Destroy;
  Hub_25384D0.Destroy;
  StrCat_24BF200.Destroy;
  Edit_24C9D10.Destroy;
  Edit_24C9C70.Destroy;
  Edit_24C8730.Destroy;
  StrCat_24BF0D0.Destroy;
  StrCat_24BEFA0.Destroy;
  Button_24C9BD0.Destroy;
  Button_24C9B30.Destroy;
  Edit_24C9A90.Destroy;
  Button_24C99F0.Destroy;
  Edit_24C98B0.Destroy;
  Edit_24C9270.Destroy;
  StrCat_24BEF08.Destroy;
  ComboBox_24C9130.Destroy;
  Edit_24C8C30.Destroy;
  ClipboardHook_24BEE70.Destroy;
  Edit_24C8AF0.Destroy;
  Edit_24C8A50.Destroy;
  StrCat_24BEDD8.Destroy;
  StrCat_24BED40.Destroy;
  StrCat_24BECA8.Destroy;
  Edit_24C89B0.Destroy;
  Button_24C8910.Destroy;
  Button_24C8870.Destroy;
  Button_24C87D0.Destroy;
  Button_24C8690.Destroy;
  Edit_24C85F0.Destroy;
  StrCat_24BEB78.Destroy;
  Button_24C8550.Destroy;
  Edit_24C84B0.Destroy;
  StrCat_24BE9B0.Destroy;
  Edit_24C8410.Destroy;
  Button_24C8370.Destroy;
  Button_24C82D0.Destroy;
  StrCat_24BEA48.Destroy;
  Edit_24C80F0.Destroy;
  Edit_24C8050.Destroy;
  EditMulti_245C450.Destroy;
  Panel_24C7C90.Destroy;
  inherited;
end;


end.
