unit hiChildPanel_2538790;

interface

uses 
  Windows,
  hiEditMulti,
  hiPanel,
  hiEdit,
  hiStrCat,
  hiButton,
  hiClipboardHook,
  hiHub,
  hiTimer,
  hiMultiBase,
  kol,Share;

type
TClassChildPanel_2538790 = class(TClassMultiBase)
 public
  EditMulti_245C510:THIEditMulti;
  Panel_24CBED0:THIPanel;
  Edit_24CBF70:THIEdit;
  Edit_24CC010:THIEdit;
  StrCat_24C0338:THIStrCat;
  Button_24CC0B0:THIButton;
  Button_24CC150:THIButton;
  Edit_24CC1F0:THIEdit;
  StrCat_24C02A0:THIStrCat;
  Edit_24CC290:THIEdit;
  Button_24CC330:THIButton;
  StrCat_24C03D0:THIStrCat;
  Edit_24CC3D0:THIEdit;
  Button_24CC470:THIButton;
  Button_24CC5B0:THIButton;
  Button_24CC650:THIButton;
  Button_24CC6F0:THIButton;
  Edit_24CC790:THIEdit;
  StrCat_24C0468:THIStrCat;
  StrCat_24C0500:THIStrCat;
  StrCat_24C0598:THIStrCat;
  Edit_24CC830:THIEdit;
  Edit_24CC8D0:THIEdit;
  ClipboardHook_24C0630:THIClipboardHook;
  Edit_24CC970:THIEdit;
  StrCat_24C06C8:THIStrCat;
  Edit_24CCAB0:THIEdit;
  Edit_24CCB50:THIEdit;
  Button_24CCBF0:THIButton;
  Edit_24CCC90:THIEdit;
  Button_24CCD30:THIButton;
  Button_24CCDD0:THIButton;
  StrCat_24C0760:THIStrCat;
  StrCat_24C07F8:THIStrCat;
  Edit_24CCE70:THIEdit;
  Edit_24CCF10:THIEdit;
  Edit_24CCFB0:THIEdit;
  StrCat_24C0890:THIStrCat;
  Hub_2538840:THIHub;
  Edit_24CC510:THIEdit;
  StrCat_24C0928:THIStrCat;
  StrCat_24C09C0:THIStrCat;
  Hub_25388F0:THIHub;
  StrCat_24C0A58:THIStrCat;
  Edit_24CD370:THIEdit;
  Button_24CD410:THIButton;
  Hub_25389A0:THIHub;
  Button_24CD5F0:THIButton;
  Button_24CD690:THIButton;
  Edit_24CD910:THIEdit;
  Edit_24CD9B0:THIEdit;
  Edit_24CDA50:THIEdit;
  Edit_24CDCD0:THIEdit;
  Edit_24CDD70:THIEdit;
  StrCat_24C0D50:THIStrCat;
  StrCat_24C0DE8:THIStrCat;
  Timer_24C0E80:THITimer;
  Edit_24CDE10:THIEdit;
  Edit_24CDEB0:THIEdit;
  Edit_24CDF50:THIEdit;
  Button_4649190:THIButton;
  Button_46490F0:THIButton;
  Button_4648330:THIButton;
  StrCat_24C2218:THIStrCat;
  StrCat_24C2348:THIStrCat;
  StrCat_24C2478:THIStrCat;
  Button_4649050:THIButton;
  StrCat_24C2640:THIStrCat;
  Button_46492D0:THIButton;
  Button_4649230:THIButton;
  StrCat_24C2808:THIStrCat;
  StrCat_24C2938:THIStrCat;

  ParentClass:TObject;

  constructor Create(_parent:pointer; _Control:PControl; _ParentClass:TObject);
  destructor Destroy; override;
 end;

  function Create_hiChildPanel_2538790(_parent:pointer; Control:PControl; _ParentClass:TObject):THiEditMulti;

implementation


function Create_hiChildPanel_2538790;
begin
  Result := THiEditMulti(TClassChildPanel_2538790.Create(_parent, Control, _ParentClass).Child);
end;

constructor TClassChildPanel_2538790.Create;
begin
  inherited;
  ParentClass := _ParentClass;
 //Panel_24CBED0 - Main
  Panel_24CBED0 := THIPanel.Create(_Control);
  with Panel_24CBED0 do begin
    ManFlags := 0;
    _prop_Left := 165;
    _prop_Top := 20;
    _prop_Width := 750;
    _prop_Height := 375;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar('FormTableNmap'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Caption := PChar(#0);
    _prop_BorderStyle := 0;
    _prop_BorderWidth := 1;
    _prop_BevelInner := 2;
    _prop_BevelOuter := 0;
    _prop_BevelWidth := 1;
    _prop_Alignment := 0;
    _prop_MouseCapture := False;
    Init;
  end;
//Init for EditMulti;
  EditMulti_245C510 := THIEditMulti.Create;
  with EditMulti_245C510 do begin
    SetLength(Works,1);
    SetLength(Vars, 0);
  end;
//Init for Edit;
  Edit_24CBF70 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CBF70 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CC010 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CC010 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 285;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C0338 := THIStrCat.Create;
  with StrCat_24C0338 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Button;
  Button_24CC0B0 := THIButton.Create(Panel_24CBED0.Control);
  with Button_24CC0B0 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 20;
    _prop_Width := 80;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('nmap'#0);
    _prop_Data := _DoData(PChar('nmap '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24CC150 := THIButton.Create(Panel_24CBED0.Control);
  with Button_24CC150 do begin
    ManFlags := 0;
    _prop_Left := 85;
    _prop_Top := 85;
    _prop_Width := 40;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Показывать только открытые порты.'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('--open'#0);
    _prop_Data := _DoData(PChar(' --open '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Edit;
  Edit_24CC1F0 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CC1F0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 225;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C02A0 := THIStrCat.Create;
  with StrCat_24C02A0 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24CC290 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CC290 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 305;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_24CC330 := THIButton.Create(Panel_24CBED0.Control);
  with Button_24CC330 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 85;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Простое быстрое сканирование(топ 100 самых популярных портов)'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-F'#0);
    _prop_Data := _DoData(PChar(' -f '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for StrCat;
  StrCat_24C03D0 := THIStrCat.Create;
  with StrCat_24C03D0 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24CC3D0 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CC3D0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_24CC470 := THIButton.Create(Panel_24CBED0.Control);
  with Button_24CC470 do begin
    ManFlags := 0;
    _prop_Left := 85;
    _prop_Top := 110;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Сканирование с помощью SYN STEALTH(Скрытое сканирование)'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-sS'#0);
    _prop_Data := _DoData(PChar(' -sS '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24CC5B0 := THIButton.Create(Panel_24CBED0.Control);
  with Button_24CC5B0 do begin
    ManFlags := 0;
    _prop_Left := 130;
    _prop_Top := 85;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(' Эта опция выставит самые агрессивные настройки сканирования, но скорость будет гораздо выше'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-T5'#0);
    _prop_Data := _DoData(PChar(' -T5 '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24CC650 := THIButton.Create(Panel_24CBED0.Control);
  with Button_24CC650 do begin
    ManFlags := 0;
    _prop_Left := 165;
    _prop_Top := 85;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Отключить запросы к DNS, если не нужны имена хостов(Cильно увеличивает скорость сканирования)'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-n'#0);
    _prop_Data := _DoData(PChar(' -n '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24CC6F0 := THIButton.Create(Panel_24CBED0.Control);
  with Button_24CC6F0 do begin
    ManFlags := 0;
    _prop_Left := 200;
    _prop_Top := 85;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Отключением Ping сканирования(Повышает скорость)'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-Pn'#0);
    _prop_Data := _DoData(PChar(' -Pn '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Edit;
  Edit_24CC790 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CC790 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 265;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C0468 := THIStrCat.Create;
  with StrCat_24C0468 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24C0500 := THIStrCat.Create;
  with StrCat_24C0500 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24C0598 := THIStrCat.Create;
  with StrCat_24C0598 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24CC830 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CC830 do begin
    ManFlags := 0;
    _prop_Left := 215;
    _prop_Top := 20;
    _prop_Width := 460;
    _prop_Height := 25;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CC8D0 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CC8D0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 325;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for ClipboardHook;
  ClipboardHook_24C0630 := THIClipboardHook.Create(Panel_24CBED0.Control);
  with ClipboardHook_24C0630 do begin
    _prop_DataStream := 1;
    _prop_NextHook := 0;
  end;
//Init for Edit;
  Edit_24CC970 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CC970 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C06C8 := THIStrCat.Create;
  with StrCat_24C06C8 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24CCAB0 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CCAB0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 245;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CCB50 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CCB50 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 60;
    _prop_Width := 115;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('ip'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_24CCBF0 := THIButton.Create(Panel_24CBED0.Control);
  with Button_24CCBF0 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 110;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Определение типа операционной системы по открытым портам.'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-O'#0);
    _prop_Data := _DoData(PChar(' -O '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Edit;
  Edit_24CCC90 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CCC90 do begin
    ManFlags := 0;
    _prop_Left := 205;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Указание порта (отличного от дефолтного) сервиса'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('Port'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := False;
    Init;
  end;
//Init for Button;
  Button_24CCD30 := THIButton.Create(Panel_24CBED0.Control);
  with Button_24CCD30 do begin
    ManFlags := 0;
    _prop_Left := 165;
    _prop_Top := 60;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('IP'#0);
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24CCDD0 := THIButton.Create(Panel_24CBED0.Control);
  with Button_24CCDD0 do begin
    ManFlags := 0;
    _prop_Left := 255;
    _prop_Top := 60;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Указание порта (отличного от дефолтного) сервиса'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('Port'#0);
    _prop_Data := _DoData(PChar(' -p '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for StrCat;
  StrCat_24C0760 := THIStrCat.Create;
  with StrCat_24C0760 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24C07F8 := THIStrCat.Create;
  with StrCat_24C07F8 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24CCE70 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CCE70 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CCF10 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CCF10 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 185;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CCFB0 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CCFB0 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C0890 := THIStrCat.Create;
  with StrCat_24C0890 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Hub;
  Hub_2538840 := THIHub.Create;
  with Hub_2538840 do begin
    _prop_InCount := 1;
    _prop_OutCount := 2;
  end;
//Init for Edit;
  Edit_24CC510 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CC510 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 345;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C0928 := THIStrCat.Create;
  with StrCat_24C0928 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24C09C0 := THIStrCat.Create;
  with StrCat_24C09C0 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Hub;
  Hub_25388F0 := THIHub.Create;
  with Hub_25388F0 do begin
    _prop_InCount := 1;
    _prop_OutCount := 2;
  end;
//Init for StrCat;
  StrCat_24C0A58 := THIStrCat.Create;
  with StrCat_24C0A58 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24CD370 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CD370 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_24CD410 := THIButton.Create(Panel_24CBED0.Control);
  with Button_24CD410 do begin
    ManFlags := 0;
    _prop_Left := 680;
    _prop_Top := 20;
    _prop_Width := 55;
    _prop_Height := 25;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('COPY'#0);
    _prop_Data := _DoData(PChar('Код скопирован в буфер обмена!'#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Hub;
  Hub_25389A0 := THIHub.Create;
  with Hub_25389A0 do begin
    _prop_InCount := 1;
    _prop_OutCount := 2;
  end;
//Init for Button;
  Button_24CD5F0 := THIButton.Create(Panel_24CBED0.Control);
  with Button_24CD5F0 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 135;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Скрипт, который проверяет FTP сервера на возможность залогиниться анонимно'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('ftp-anon'#0);
    _prop_Data := _DoData(PChar(' --script=ftp-anon '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24CD690 := THIButton.Create(Panel_24CBED0.Control);
  with Button_24CD690 do begin
    ManFlags := 0;
    _prop_Left := 105;
    _prop_Top := 135;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Стандартного набор скриптов(Выводит много интересной информации)'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-sC'#0);
    _prop_Data := _DoData(PChar(' -sC '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Edit;
  Edit_24CD910 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CD910 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CD9B0 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CD9B0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CDA50 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CDA50 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CDCD0 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CDCD0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CDD70 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CDD70 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C0D50 := THIStrCat.Create;
  with StrCat_24C0D50 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24C0DE8 := THIStrCat.Create;
  with StrCat_24C0DE8 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Timer;
  Timer_24C0E80 := THITimer.Create;
  with Timer_24C0E80 do begin
    _prop_Interval := 3000;
    _prop_Enable := False;
    _prop_AutoStop := 1;
    _prop_OverCall := 0;
  end;
//Init for Edit;
  Edit_24CDE10 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CDE10 do begin
    ManFlags := 0;
    _prop_Left := 1315;
    _prop_Top := 370;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(' '#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CDEB0 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CDEB0 do begin
    ManFlags := 0;
    _prop_Left := 1285;
    _prop_Top := 305;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',10,0,255,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('Код скопирован в буфер обмена!'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CDF50 := THIEdit.Create(Panel_24CBED0.Control);
  with Edit_24CDF50 do begin
    ManFlags := 0;
    _prop_Left := 475;
    _prop_Top := 50;
    _prop_Width := 260;
    _prop_Height := 25;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',10,1,255,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := True;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_4649190 := THIButton.Create(Panel_24CBED0.Control);
  with Button_4649190 do begin
    ManFlags := 0;
    _prop_Left := 120;
    _prop_Top := 110;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Сохранить весь вывод программы в текстовый файл'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-oN'#0);
    _prop_Data := _DoData(PChar(' -oN output.txt '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_46490F0 := THIButton.Create(Panel_24CBED0.Control);
  with Button_46490F0 do begin
    ManFlags := 0;
    _prop_Left := 155;
    _prop_Top := 110;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Сохранить весь вывод программы в xml файл'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-oX'#0);
    _prop_Data := _DoData(PChar(' -oX output.xml '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_4648330 := THIButton.Create(Panel_24CBED0.Control);
  with Button_4648330 do begin
    ManFlags := 0;
    _prop_Left := 190;
    _prop_Top := 110;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Сохранить вывод программы в трех доступных вариантах сразу'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-oA'#0);
    _prop_Data := _DoData(PChar(' -oA file '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for StrCat;
  StrCat_24C2218 := THIStrCat.Create;
  with StrCat_24C2218 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24C2348 := THIStrCat.Create;
  with StrCat_24C2348 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24C2478 := THIStrCat.Create;
  with StrCat_24C2478 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Button;
  Button_4649050 := THIButton.Create(Panel_24CBED0.Control);
  with Button_4649050 do begin
    ManFlags := 0;
    _prop_Left := 140;
    _prop_Top := 135;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Ping сканирование'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-sP'#0);
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for StrCat;
  StrCat_24C2640 := THIStrCat.Create;
  with StrCat_24C2640 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Button;
  Button_46492D0 := THIButton.Create(Panel_24CBED0.Control);
  with Button_46492D0 do begin
    ManFlags := 0;
    _prop_Left := 175;
    _prop_Top := 135;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Основная доступная информация об удаленном хосте '#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-A'#0);
    _prop_Data := _DoData(PChar(' -A '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_4649230 := THIButton.Create(Panel_24CBED0.Control);
  with Button_4649230 do begin
    ManFlags := 0;
    _prop_Left := 210;
    _prop_Top := 135;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-v'#0);
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for StrCat;
  StrCat_24C2808 := THIStrCat.Create;
  with StrCat_24C2808 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24C2938 := THIStrCat.Create;
  with StrCat_24C2938 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
  Child := EditMulti_245C510;
  EditMulti_245C510.MainClass := Self;
  EditMulti_245C510.Parent := _parent;
 //Make all connection in scheme
  EditMulti_245C510.Works[0]               := _DoEvent(Panel_24CBED0._work_doVisible,1);
  Edit_24CBF70._event_onChange             := _DoEvent(Edit_24CD910._work_doText,0);
  Edit_24CC010._event_onChange             := _DoEvent(Edit_24CC790._work_doText,0);
  StrCat_24C0338._event_onStrCat           := _DoEvent(Edit_24CC790._work_doText,0);
  StrCat_24C0338._data_Str1                := _DoEvent(Edit_24CC010._var_Text,0);
  Button_24CC0B0._event_onClick            := _DoEvent(Edit_24CBF70._work_doText,0);
  Button_24CC150._event_onClick            := _DoEvent(StrCat_24C02A0._work_doStrCat,0);
  Edit_24CC1F0._event_onChange             := _DoEvent(Edit_24CC290._work_doText,0);
  StrCat_24C02A0._event_onStrCat           := _DoEvent(Edit_24CDA50._work_doText,0);
  StrCat_24C02A0._data_Str1                := _DoEvent(Edit_24CD9B0._var_Text,0);
  Edit_24CC290._event_onChange             := _DoEvent(Edit_24CC3D0._work_doText,0);
  Button_24CC330._event_onClick            := _DoEvent(StrCat_24C03D0._work_doStrCat,0);
  StrCat_24C03D0._event_onStrCat           := _DoEvent(Edit_24CD9B0._work_doText,0);
  StrCat_24C03D0._data_Str1                := _DoEvent(Edit_24CDD70._var_Text,0);
  Edit_24CC3D0._event_onChange             := _DoEvent(Edit_24CC010._work_doText,0);
  Button_24CC470._event_onClick            := _DoEvent(StrCat_24C0338._work_doStrCat,0);
  Button_24CC5B0._event_onClick            := _DoEvent(StrCat_24C0468._work_doStrCat,0);
  Button_24CC650._event_onClick            := _DoEvent(StrCat_24C0500._work_doStrCat,0);
  Button_24CC6F0._event_onClick            := _DoEvent(StrCat_24C0598._work_doStrCat,0);
  Edit_24CC790._event_onChange             := _DoEvent(Edit_24CC8D0._work_doText,0);
  StrCat_24C0468._event_onStrCat           := _DoEvent(Edit_24CC1F0._work_doText,0);
  StrCat_24C0468._data_Str1                := _DoEvent(Edit_24CDA50._var_Text,0);
  StrCat_24C0500._event_onStrCat           := _DoEvent(Edit_24CC290._work_doText,0);
  StrCat_24C0500._data_Str1                := _DoEvent(Edit_24CC1F0._var_Text,0);
  StrCat_24C0598._event_onStrCat           := _DoEvent(Edit_24CC3D0._work_doText,0);
  StrCat_24C0598._data_Str1                := _DoEvent(Edit_24CC290._var_Text,0);
  Edit_24CC8D0._event_onChange             := _DoEvent(Edit_24CC510._work_doText,0);
  ClipboardHook_24C0630._data_Text         := _DoEvent(Edit_24CC830._var_Text,0);
  Edit_24CC970._event_onChange             := _DoEvent(Edit_24CCAB0._work_doText,0);
  Edit_24CCAB0._event_onChange             := _DoEvent(Edit_24CCE70._work_doText,0);
  Button_24CCBF0._event_onClick            := _DoEvent(StrCat_24C0928._work_doStrCat,0);
  Button_24CCD30._event_onClick            := _DoEvent(StrCat_24C0760._work_doStrCat,0);
  Button_24CCDD0._event_onClick            := _DoEvent(Hub_2538840.doEvent,0);
  StrCat_24C0760._event_onStrCat           := _DoEvent(Edit_24CD910._work_doText,0);
  StrCat_24C0760._data_Str1                := _DoEvent(Edit_24CBF70._var_Text,0);
  StrCat_24C0760._data_Str2                := _DoEvent(Edit_24CCB50._var_Text,0);
  StrCat_24C07F8._event_onStrCat           := _DoEvent(Edit_24CDCD0._work_doText,0);
  StrCat_24C07F8._data_Str1                := _DoEvent(Edit_24CD910._var_Text,0);
  Edit_24CCE70._event_onChange             := _DoEvent(Edit_24CD370._work_doText,0);
  Edit_24CCF10._event_onChange             := _DoEvent(Edit_24CC830._work_doText,0);
  Edit_24CCFB0._event_onChange             := _DoEvent(Edit_24CCF10._work_doText,0);
  StrCat_24C0890._event_onStrCat           := _DoEvent(Edit_24CDD70._work_doText,0);
  StrCat_24C0890._data_Str1                := _DoEvent(Edit_24CDCD0._var_Text,0);
  StrCat_24C0890._data_Str2                := _DoEvent(Edit_24CCC90._var_Text,0);
  Hub_2538840.onEvent[0]                   := _DoEvent(StrCat_24C07F8._work_doStrCat,0);
  Hub_2538840.onEvent[1]                   := _DoEvent(StrCat_24C0890._work_doStrCat,0);
  Edit_24CC510._event_onChange             := _DoEvent(Edit_24CC970._work_doText,0);
  StrCat_24C0928._event_onStrCat           := _DoEvent(Edit_24CC010._work_doText,0);
  StrCat_24C0928._data_Str1                := _DoEvent(Edit_24CC3D0._var_Text,0);
  Hub_25388F0.onEvent[0]                   := _DoEvent(StrCat_24C09C0._work_doStrCat,0);
  Hub_25388F0.onEvent[1]                   := _DoEvent(StrCat_24C0A58._work_doStrCat,0);
  StrCat_24C0A58._event_onStrCat           := _DoEvent(Edit_24CC830._work_doText,0);
  Edit_24CD370._event_onChange             := _DoEvent(Edit_24CCFB0._work_doText,0);
  Button_24CD410._event_onClick            := _DoEvent(Hub_25389A0.doEvent,0);
  Hub_25389A0.onEvent[0]                   := _DoEvent(ClipboardHook_24C0630._work_doSetText,0);
  Hub_25389A0.onEvent[1]                   := _DoEvent(Edit_24CDEB0._work_doText,0);
  Button_24CD5F0._event_onClick            := _DoEvent(StrCat_24C0D50._work_doStrCat,0);
  Button_24CD690._event_onClick            := _DoEvent(StrCat_24C0DE8._work_doStrCat,0);
  Edit_24CD910._event_onChange             := _DoEvent(Edit_24CDCD0._work_doText,0);
  Edit_24CD9B0._event_onChange             := _DoEvent(Edit_24CDA50._work_doText,0);
  Edit_24CDA50._event_onChange             := _DoEvent(Edit_24CC1F0._work_doText,0);
  Edit_24CDCD0._event_onChange             := _DoEvent(Edit_24CDD70._work_doText,0);
  Edit_24CDD70._event_onChange             := _DoEvent(Edit_24CD9B0._work_doText,0);
  StrCat_24C0D50._event_onStrCat           := _DoEvent(Edit_24CCAB0._work_doText,0);
  StrCat_24C0D50._data_Str1                := _DoEvent(Edit_24CC970._var_Text,0);
  StrCat_24C0DE8._event_onStrCat           := _DoEvent(Edit_24CCE70._work_doText,0);
  StrCat_24C0DE8._data_Str1                := _DoEvent(Edit_24CCAB0._var_Text,0);
  Timer_24C0E80._event_onTimer             := _DoEvent(Edit_24CDE10._work_doText,0);
  Edit_24CDE10._event_onChange             := _DoEvent(Edit_24CDF50._work_doText,0);
  Edit_24CDEB0._event_onChange             := _DoEvent(Edit_24CDF50._work_doText,0);
  Edit_24CDF50._event_onChange             := _DoEvent(Timer_24C0E80._work_doTimer,0);
  Button_4649190._event_onClick            := _DoEvent(StrCat_24C2218._work_doStrCat,0);
  Button_46490F0._event_onClick            := _DoEvent(StrCat_24C2348._work_doStrCat,0);
  Button_4648330._event_onClick            := _DoEvent(StrCat_24C2478._work_doStrCat,0);
  StrCat_24C2218._event_onStrCat           := _DoEvent(Edit_24CC8D0._work_doText,0);
  StrCat_24C2218._data_Str1                := _DoEvent(Edit_24CC790._var_Text,0);
  StrCat_24C2348._event_onStrCat           := _DoEvent(Edit_24CC510._work_doText,0);
  StrCat_24C2348._data_Str1                := _DoEvent(Edit_24CC8D0._var_Text,0);
  StrCat_24C2478._event_onStrCat           := _DoEvent(Edit_24CC970._work_doText,0);
  StrCat_24C2478._data_Str1                := _DoEvent(Edit_24CC510._var_Text,0);
  Button_4649050._event_onClick            := _DoEvent(StrCat_24C2640._work_doStrCat,0);
  StrCat_24C2640._event_onStrCat           := _DoEvent(Edit_24CD370._work_doText,0);
  StrCat_24C2640._data_Str1                := _DoEvent(Edit_24CCE70._var_Text,0);
  Button_46492D0._event_onClick            := _DoEvent(StrCat_24C2808._work_doStrCat,0);
  Button_4649230._event_onClick            := _DoEvent(StrCat_24C2938._work_doStrCat,0);
  StrCat_24C2808._event_onStrCat           := _DoEvent(Edit_24CCFB0._work_doText,0);
  StrCat_24C2808._data_Str1                := _DoEvent(Edit_24CD370._var_Text,0);
  StrCat_24C2938._data_Str1                := _DoEvent(Edit_24CCFB0._var_Text,0);
  Panel_24CBED0._prop_HintManager := nil;
  Panel_24CBED0._prop_Layout := nil;
  Edit_24CBF70._prop_HintManager := nil;
  Edit_24CBF70._prop_Layout := nil;
  Edit_24CC010._prop_HintManager := nil;
  Edit_24CC010._prop_Layout := nil;
  Button_24CC0B0._prop_HintManager := nil;
  Button_24CC0B0._prop_Layout := nil;
  Button_24CC150._prop_HintManager := nil;
  Button_24CC150._prop_Layout := nil;
  Edit_24CC1F0._prop_HintManager := nil;
  Edit_24CC1F0._prop_Layout := nil;
  Edit_24CC290._prop_HintManager := nil;
  Edit_24CC290._prop_Layout := nil;
  Button_24CC330._prop_HintManager := nil;
  Button_24CC330._prop_Layout := nil;
  Edit_24CC3D0._prop_HintManager := nil;
  Edit_24CC3D0._prop_Layout := nil;
  Button_24CC470._prop_HintManager := nil;
  Button_24CC470._prop_Layout := nil;
  Button_24CC5B0._prop_HintManager := nil;
  Button_24CC5B0._prop_Layout := nil;
  Button_24CC650._prop_HintManager := nil;
  Button_24CC650._prop_Layout := nil;
  Button_24CC6F0._prop_HintManager := nil;
  Button_24CC6F0._prop_Layout := nil;
  Edit_24CC790._prop_HintManager := nil;
  Edit_24CC790._prop_Layout := nil;
  Edit_24CC830._prop_HintManager := nil;
  Edit_24CC830._prop_Layout := nil;
  Edit_24CC8D0._prop_HintManager := nil;
  Edit_24CC8D0._prop_Layout := nil;
  Edit_24CC970._prop_HintManager := nil;
  Edit_24CC970._prop_Layout := nil;
  Edit_24CCAB0._prop_HintManager := nil;
  Edit_24CCAB0._prop_Layout := nil;
  Edit_24CCB50._prop_HintManager := nil;
  Edit_24CCB50._prop_Layout := nil;
  Button_24CCBF0._prop_HintManager := nil;
  Button_24CCBF0._prop_Layout := nil;
  Edit_24CCC90._prop_HintManager := nil;
  Edit_24CCC90._prop_Layout := nil;
  Button_24CCD30._prop_HintManager := nil;
  Button_24CCD30._prop_Layout := nil;
  Button_24CCDD0._prop_HintManager := nil;
  Button_24CCDD0._prop_Layout := nil;
  Edit_24CCE70._prop_HintManager := nil;
  Edit_24CCE70._prop_Layout := nil;
  Edit_24CCF10._prop_HintManager := nil;
  Edit_24CCF10._prop_Layout := nil;
  Edit_24CCFB0._prop_HintManager := nil;
  Edit_24CCFB0._prop_Layout := nil;
  Edit_24CC510._prop_HintManager := nil;
  Edit_24CC510._prop_Layout := nil;
  Edit_24CD370._prop_HintManager := nil;
  Edit_24CD370._prop_Layout := nil;
  Button_24CD410._prop_HintManager := nil;
  Button_24CD410._prop_Layout := nil;
  Button_24CD5F0._prop_HintManager := nil;
  Button_24CD5F0._prop_Layout := nil;
  Button_24CD690._prop_HintManager := nil;
  Button_24CD690._prop_Layout := nil;
  Edit_24CD910._prop_HintManager := nil;
  Edit_24CD910._prop_Layout := nil;
  Edit_24CD9B0._prop_HintManager := nil;
  Edit_24CD9B0._prop_Layout := nil;
  Edit_24CDA50._prop_HintManager := nil;
  Edit_24CDA50._prop_Layout := nil;
  Edit_24CDCD0._prop_HintManager := nil;
  Edit_24CDCD0._prop_Layout := nil;
  Edit_24CDD70._prop_HintManager := nil;
  Edit_24CDD70._prop_Layout := nil;
  Edit_24CDE10._prop_HintManager := nil;
  Edit_24CDE10._prop_Layout := nil;
  Edit_24CDEB0._prop_HintManager := nil;
  Edit_24CDEB0._prop_Layout := nil;
  Edit_24CDF50._prop_HintManager := nil;
  Edit_24CDF50._prop_Layout := nil;
  Button_4649190._prop_HintManager := nil;
  Button_4649190._prop_Layout := nil;
  Button_46490F0._prop_HintManager := nil;
  Button_46490F0._prop_Layout := nil;
  Button_4648330._prop_HintManager := nil;
  Button_4648330._prop_Layout := nil;
  Button_4649050._prop_HintManager := nil;
  Button_4649050._prop_Layout := nil;
  Button_46492D0._prop_HintManager := nil;
  Button_46492D0._prop_Layout := nil;
  Button_4649230._prop_HintManager := nil;
  Button_4649230._prop_Layout := nil;
  Panel_24CBED0.Control.Tabulate;

  ParentElement := Panel_24CBED0;
end;

destructor TClassChildPanel_2538790.Destroy;
begin
  StrCat_24C2938.Destroy;
  StrCat_24C2808.Destroy;
  Button_4649230.Destroy;
  Button_46492D0.Destroy;
  StrCat_24C2640.Destroy;
  Button_4649050.Destroy;
  StrCat_24C2478.Destroy;
  StrCat_24C2348.Destroy;
  StrCat_24C2218.Destroy;
  Button_4648330.Destroy;
  Button_46490F0.Destroy;
  Button_4649190.Destroy;
  Edit_24CDF50.Destroy;
  Edit_24CDEB0.Destroy;
  Edit_24CDE10.Destroy;
  Timer_24C0E80.Destroy;
  StrCat_24C0DE8.Destroy;
  StrCat_24C0D50.Destroy;
  Edit_24CDD70.Destroy;
  Edit_24CDCD0.Destroy;
  Edit_24CDA50.Destroy;
  Edit_24CD9B0.Destroy;
  Edit_24CD910.Destroy;
  Button_24CD690.Destroy;
  Button_24CD5F0.Destroy;
  Hub_25389A0.Destroy;
  Button_24CD410.Destroy;
  Edit_24CD370.Destroy;
  StrCat_24C0A58.Destroy;
  Hub_25388F0.Destroy;
  StrCat_24C09C0.Destroy;
  StrCat_24C0928.Destroy;
  Edit_24CC510.Destroy;
  Hub_2538840.Destroy;
  StrCat_24C0890.Destroy;
  Edit_24CCFB0.Destroy;
  Edit_24CCF10.Destroy;
  Edit_24CCE70.Destroy;
  StrCat_24C07F8.Destroy;
  StrCat_24C0760.Destroy;
  Button_24CCDD0.Destroy;
  Button_24CCD30.Destroy;
  Edit_24CCC90.Destroy;
  Button_24CCBF0.Destroy;
  Edit_24CCB50.Destroy;
  Edit_24CCAB0.Destroy;
  StrCat_24C06C8.Destroy;
  Edit_24CC970.Destroy;
  ClipboardHook_24C0630.Destroy;
  Edit_24CC8D0.Destroy;
  Edit_24CC830.Destroy;
  StrCat_24C0598.Destroy;
  StrCat_24C0500.Destroy;
  StrCat_24C0468.Destroy;
  Edit_24CC790.Destroy;
  Button_24CC6F0.Destroy;
  Button_24CC650.Destroy;
  Button_24CC5B0.Destroy;
  Button_24CC470.Destroy;
  Edit_24CC3D0.Destroy;
  StrCat_24C03D0.Destroy;
  Button_24CC330.Destroy;
  Edit_24CC290.Destroy;
  StrCat_24C02A0.Destroy;
  Edit_24CC1F0.Destroy;
  Button_24CC150.Destroy;
  Button_24CC0B0.Destroy;
  StrCat_24C0338.Destroy;
  Edit_24CC010.Destroy;
  Edit_24CBF70.Destroy;
  EditMulti_245C510.Destroy;
  Panel_24CBED0.Destroy;
  inherited;
end;


end.
