unit hiChildPanel_2538A50;

interface

uses 
  Windows,
  hiEditMulti,
  hiPanel,
  hiEdit,
  hiStrCat,
  hiButton,
  hiClipboardHook,
  hiComboBox,
  hiHub,
  hiLabel,
  hiTimer,
  hiMultiBase,
  kol,Share;

type
TClassChildPanel_2538A50 = class(TClassMultiBase)
 public
  EditMulti_245D050:THIEditMulti;
  Panel_24CD050:THIPanel;
  Edit_24CD730:THIEdit;
  Edit_24CD870:THIEdit;
  StrCat_24C0AF0:THIStrCat;
  Button_24CD7D0:THIButton;
  Button_24CD550:THIButton;
  Edit_24CD0F0:THIEdit;
  StrCat_24C0CB8:THIStrCat;
  Edit_24CD4B0:THIEdit;
  Button_4649410:THIButton;
  StrCat_24C0C20:THIStrCat;
  Edit_4649550:THIEdit;
  Button_4649370:THIButton;
  Button_4649730:THIButton;
  Button_46497D0:THIButton;
  Button_4649870:THIButton;
  Edit_4649910:THIEdit;
  StrCat_24C2B00:THIStrCat;
  StrCat_24C2B98:THIStrCat;
  StrCat_24C2C30:THIStrCat;
  Edit_46499B0:THIEdit;
  Edit_4649A50:THIEdit;
  ClipboardHook_24C2CC8:THIClipboardHook;
  Edit_4649AF0:THIEdit;
  ComboBox_4649B90:THIComboBox;
  StrCat_24C2D60:THIStrCat;
  Edit_4649C30:THIEdit;
  Edit_4649CD0:THIEdit;
  Button_4649D70:THIButton;
  Edit_4649E10:THIEdit;
  Button_4649EB0:THIButton;
  Button_4649F50:THIButton;
  StrCat_24C2DF8:THIStrCat;
  StrCat_24C2F28:THIStrCat;
  Edit_4649690:THIEdit;
  Edit_46495F0:THIEdit;
  Edit_46494B0:THIEdit;
  StrCat_24C3058:THIStrCat;
  Hub_253B910:THIHub;
  Edit_4649FF0:THIEdit;
  StrCat_24C3188:THIStrCat;
  Label_464A090:THILabel;
  Label_464A130:THILabel;
  Label_464A1D0:THILabel;
  Edit_464A270:THIEdit;
  Button_464A310:THIButton;
  StrCat_24C32B8:THIStrCat;
  Hub_2538B00:THIHub;
  StrCat_24C3350:THIStrCat;
  Edit_464A3B0:THIEdit;
  Button_464A450:THIButton;
  Hub_253B9C0:THIHub;
  Button_464A4F0:THIButton;
  Button_464A590:THIButton;
  Button_464A630:THIButton;
  Button_464A6D0:THIButton;
  Label_464A770:THILabel;
  Edit_464A810:THIEdit;
  Edit_464A8B0:THIEdit;
  StrCat_24C3810:THIStrCat;
  StrCat_24C38A8:THIStrCat;
  Edit_464A950:THIEdit;
  Edit_464A9F0:THIEdit;
  Hub_253BA70:THIHub;
  Hub_253BB20:THIHub;
  StrCat_24C39D8:THIStrCat;
  Edit_464AA90:THIEdit;
  StrCat_24C3B08:THIStrCat;
  Label_464AB30:THILabel;
  Label_464ABD0:THILabel;
  Label_464AC70:THILabel;
  Edit_464AD10:THIEdit;
  Edit_464ADB0:THIEdit;
  StrCat_24C3CD0:THIStrCat;
  StrCat_24C3E00:THIStrCat;
  Timer_24C3F30:THITimer;
  Edit_464AE50:THIEdit;
  Edit_464AEF0:THIEdit;
  Edit_464AF90:THIEdit;

  ParentClass:TObject;

  constructor Create(_parent:pointer; _Control:PControl; _ParentClass:TObject);
  destructor Destroy; override;
 end;

  function Create_hiChildPanel_2538A50(_parent:pointer; Control:PControl; _ParentClass:TObject):THiEditMulti;

implementation


function Create_hiChildPanel_2538A50;
begin
  Result := THiEditMulti(TClassChildPanel_2538A50.Create(_parent, Control, _ParentClass).Child);
end;

constructor TClassChildPanel_2538A50.Create;
begin
  inherited;
  ParentClass := _ParentClass;
 //Panel_24CD050 - Main
  Panel_24CD050 := THIPanel.Create(_Control);
  with Panel_24CD050 do begin
    ManFlags := 0;
    _prop_Left := 165;
    _prop_Top := 20;
    _prop_Width := 750;
    _prop_Height := 375;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar('FormTableHydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Caption := PChar(#0);
    _prop_BorderStyle := 0;
    _prop_BorderWidth := 1;
    _prop_BevelInner := 2;
    _prop_BevelOuter := 0;
    _prop_BevelWidth := 1;
    _prop_Alignment := 0;
    _prop_MouseCapture := False;
    Init;
  end;
//Init for EditMulti;
  EditMulti_245D050 := THIEditMulti.Create;
  with EditMulti_245D050 do begin
    SetLength(Works,1);
    SetLength(Vars, 0);
  end;
//Init for Edit;
  Edit_24CD730 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_24CD730 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_24CD870 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_24CD870 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 285;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C0AF0 := THIStrCat.Create;
  with StrCat_24C0AF0 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Button;
  Button_24CD7D0 := THIButton.Create(Panel_24CD050.Control);
  with Button_24CD7D0 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 20;
    _prop_Width := 80;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('hydra'#0);
    _prop_Data := _DoData(PChar('hydra '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_24CD550 := THIButton.Create(Panel_24CD050.Control);
  with Button_24CD550 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 120;
    _prop_Width := 80;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Записать подобранную пару логин/пароль в файл, вместо того чтоб просто вывести в stdout'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('Output *.txt'#0);
    _prop_Data := _DoData(PChar(' -o result.log '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Edit;
  Edit_24CD0F0 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_24CD0F0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 225;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C0CB8 := THIStrCat.Create;
  with StrCat_24C0CB8 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_24CD4B0 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_24CD4B0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 305;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_4649410 := THIButton.Create(Panel_24CD050.Control);
  with Button_4649410 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 145;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Прекратить работу, как только первая пара логин:пароль будет подобрана, только для текущего хоста.'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-f'#0);
    _prop_Data := _DoData(PChar('-f '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for StrCat;
  StrCat_24C0C20 := THIStrCat.Create;
  with StrCat_24C0C20 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_4649550 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_4649550 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_4649370 := THIButton.Create(Panel_24CD050.Control);
  with Button_4649370 do begin
    ManFlags := 0;
    _prop_Left := 325;
    _prop_Top := 81;
    _prop_Width := 75;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Использовать список логинов и паролей из указанных файлов'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('login + pass'#0);
    _prop_Data := _DoData(PChar('-L login.txt -P pass.txt '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_4649730 := THIButton.Create(Panel_24CD050.Control);
  with Button_4649730 do begin
    ManFlags := 0;
    _prop_Left := 100;
    _prop_Top := 145;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Прекратить работу, как только первая пара логин:пароль будет подобрана, глобально.'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-F'#0);
    _prop_Data := _DoData(PChar('-F '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_46497D0 := THIButton.Create(Panel_24CD050.Control);
  with Button_46497D0 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 170;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Более подробный вывод информации о процессе '#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-v'#0);
    _prop_Data := _DoData(PChar('-v '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_4649870 := THIButton.Create(Panel_24CD050.Control);
  with Button_4649870 do begin
    ManFlags := 0;
    _prop_Left := 100;
    _prop_Top := 170;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Выводить каждый подбираемый логин + пароль '#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('-V'#0);
    _prop_Data := _DoData(PChar('-V '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Edit;
  Edit_4649910 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_4649910 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 265;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C2B00 := THIStrCat.Create;
  with StrCat_24C2B00 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24C2B98 := THIStrCat.Create;
  with StrCat_24C2B98 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24C2C30 := THIStrCat.Create;
  with StrCat_24C2C30 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_46499B0 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_46499B0 do begin
    ManFlags := 0;
    _prop_Left := 215;
    _prop_Top := 20;
    _prop_Width := 460;
    _prop_Height := 25;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_4649A50 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_4649A50 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 325;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for ClipboardHook;
  ClipboardHook_24C2CC8 := THIClipboardHook.Create(Panel_24CD050.Control);
  with ClipboardHook_24C2CC8 do begin
    _prop_DataStream := 1;
    _prop_NextHook := 0;
  end;
//Init for Edit;
  Edit_4649AF0 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_4649AF0 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for ComboBox;
  ComboBox_4649B90 := THIComboBox.Create(Panel_24CD050.Control);
  with ComboBox_4649B90 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 220;
    _prop_Width := 75;
    _prop_Height := 21;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Сервис'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_FileName := PChar(#0);
    _prop_Strings := PChar(' http-get'#13#10' ssh'#13#10' ftp'#0);
    _prop_AddType := 0;
    _prop_Text := PChar('ComboBox'#0);
    _prop_DataType := 1;
    _prop_ReadOnly := 0;
    _prop_Sort := False;
    _prop_ItemHeight := 20;
    Init;
  end;
//Init for StrCat;
  StrCat_24C2D60 := THIStrCat.Create;
  with StrCat_24C2D60 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_4649C30 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_4649C30 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 245;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_4649CD0 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_4649CD0 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 195;
    _prop_Width := 90;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('ip'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_4649D70 := THIButton.Create(Panel_24CD050.Control);
  with Button_4649D70 do begin
    ManFlags := 0;
    _prop_Left := 270;
    _prop_Top := 195;
    _prop_Width := 40;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Файл со списком целей для брутфорса (можно с указанием порта через двоеточие), по одному на строку.'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('IP-list'#0);
    _prop_Data := _DoData(PChar('-M iplist.txt '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Edit;
  Edit_4649E10 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_4649E10 do begin
    ManFlags := 0;
    _prop_Left := 170;
    _prop_Top := 195;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Указание порта (отличного от дефолтного) сервиса'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('Port'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := False;
    Init;
  end;
//Init for Button;
  Button_4649EB0 := THIButton.Create(Panel_24CD050.Control);
  with Button_4649EB0 do begin
    ManFlags := 0;
    _prop_Left := 140;
    _prop_Top := 195;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('IP'#0);
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_4649F50 := THIButton.Create(Panel_24CD050.Control);
  with Button_4649F50 do begin
    ManFlags := 0;
    _prop_Left := 220;
    _prop_Top := 195;
    _prop_Width := 30;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Указание порта (отличного от дефолтного) сервиса'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('Port'#0);
    _prop_Data := _DoData(PChar(' -s '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for StrCat;
  StrCat_24C2DF8 := THIStrCat.Create;
  with StrCat_24C2DF8 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24C2F28 := THIStrCat.Create;
  with StrCat_24C2F28 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_4649690 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_4649690 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_46495F0 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_46495F0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 185;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_46494B0 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_46494B0 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C3058 := THIStrCat.Create;
  with StrCat_24C3058 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Hub;
  Hub_253B910 := THIHub.Create;
  with Hub_253B910 do begin
    _prop_InCount := 1;
    _prop_OutCount := 2;
  end;
//Init for Edit;
  Edit_4649FF0 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_4649FF0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 345;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C3188 := THIStrCat.Create;
  with StrCat_24C3188 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Label;
  Label_464A090 := THILabel.Create(Panel_24CD050.Control);
  with Label_464A090 do begin
    ManFlags := 0;
    _prop_Left := 81;
    _prop_Top := 145;
    _prop_Width := 20;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',12,1,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Transparent := False;
    _prop_Caption := PChar('or'#0);
    _prop_AutoSize := True;
    _prop_Alignment := taLeft;
    _prop_ColorHover := 0;
    _prop_Underline := False;
    Init;
  end;
//Init for Label;
  Label_464A130 := THILabel.Create(Panel_24CD050.Control);
  with Label_464A130 do begin
    ManFlags := 0;
    _prop_Left := 81;
    _prop_Top := 170;
    _prop_Width := 20;
    _prop_Height := 24;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',12,1,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Transparent := False;
    _prop_Caption := PChar('or'#0);
    _prop_AutoSize := True;
    _prop_Alignment := taLeft;
    _prop_ColorHover := 0;
    _prop_Underline := False;
    Init;
  end;
//Init for Label;
  Label_464A1D0 := THILabel.Create(Panel_24CD050.Control);
  with Label_464A1D0 do begin
    ManFlags := 0;
    _prop_Left := 251;
    _prop_Top := 193;
    _prop_Width := 20;
    _prop_Height := 24;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',12,1,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Transparent := False;
    _prop_Caption := PChar('or'#0);
    _prop_AutoSize := True;
    _prop_Alignment := taLeft;
    _prop_ColorHover := 0;
    _prop_Underline := False;
    Init;
  end;
//Init for Edit;
  Edit_464A270 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_464A270 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 245;
    _prop_Width := 220;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Путь, который закрыт для нас запросом пары логин:пароль /example/'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('/example/'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_464A310 := THIButton.Create(Panel_24CD050.Control);
  with Button_464A310 do begin
    ManFlags := 0;
    _prop_Left := 270;
    _prop_Top := 245;
    _prop_Width := 40;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Путь, который закрыт для нас запросом пары логин:пароль /example/'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('Paste'#0);
    _prop_Data := _DoData(PChar(' '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for StrCat;
  StrCat_24C32B8 := THIStrCat.Create;
  with StrCat_24C32B8 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Hub;
  Hub_2538B00 := THIHub.Create;
  with Hub_2538B00 do begin
    _prop_InCount := 1;
    _prop_OutCount := 2;
  end;
//Init for StrCat;
  StrCat_24C3350 := THIStrCat.Create;
  with StrCat_24C3350 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_464A3B0 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_464A3B0 do begin
    ManFlags := 0;
    _prop_Left := 1390;
    _prop_Top := 60;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar('hydra'#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Button;
  Button_464A450 := THIButton.Create(Panel_24CD050.Control);
  with Button_464A450 do begin
    ManFlags := 0;
    _prop_Left := 680;
    _prop_Top := 20;
    _prop_Width := 55;
    _prop_Height := 25;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('COPY'#0);
    _prop_Data := _DoData(PChar('Код скопирован в буфер обмена!'#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Hub;
  Hub_253B9C0 := THIHub.Create;
  with Hub_253B9C0 do begin
    _prop_InCount := 1;
    _prop_OutCount := 2;
  end;
//Init for Button;
  Button_464A4F0 := THIButton.Create(Panel_24CD050.Control);
  with Button_464A4F0 do begin
    ManFlags := 0;
    _prop_Left := 160;
    _prop_Top := 70;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Использовать указанный логин для попытки аутентификации'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('Paste'#0);
    _prop_Data := _DoData(PChar('-l '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_464A590 := THIButton.Create(Panel_24CD050.Control);
  with Button_464A590 do begin
    ManFlags := 0;
    _prop_Left := 160;
    _prop_Top := 95;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Использовать указанный пароль для попытки аутентификации'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('Paste'#0);
    _prop_Data := _DoData(PChar(' -p '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_464A630 := THIButton.Create(Panel_24CD050.Control);
  with Button_464A630 do begin
    ManFlags := 0;
    _prop_Left := 235;
    _prop_Top := 70;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Использовать список логинов из указанного файла'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('login-file'#0);
    _prop_Data := _DoData(PChar(' -L login.txt '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Button;
  Button_464A6D0 := THIButton.Create(Panel_24CD050.Control);
  with Button_464A6D0 do begin
    ManFlags := 0;
    _prop_Left := 235;
    _prop_Top := 95;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Использовать список паролей из указанного файла'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_Caption := PChar('pass file'#0);
    _prop_Data := _DoData(PChar(' -P pass.txt '#0));
    _prop_Flat := False;
    _prop_DefaultBtn := False;
    Init;
  end;
//Init for Label;
  Label_464A770 := THILabel.Create(Panel_24CD050.Control);
  with Label_464A770 do begin
    ManFlags := 0;
    _prop_Left := 305;
    _prop_Top := 81;
    _prop_Width := 20;
    _prop_Height := 24;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',12,1,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Transparent := False;
    _prop_Caption := PChar('or'#0);
    _prop_AutoSize := True;
    _prop_Alignment := taLeft;
    _prop_ColorHover := 0;
    _prop_Underline := False;
    Init;
  end;
//Init for Edit;
  Edit_464A810 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_464A810 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 95;
    _prop_Width := 110;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Использовать указанный пароль для попытки аутентификации'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('password'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_464A8B0 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_464A8B0 do begin
    ManFlags := 0;
    _prop_Left := 50;
    _prop_Top := 70;
    _prop_Width := 110;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar('Использовать указанный логин для попытки аутентификации'#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('login'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C3810 := THIStrCat.Create;
  with StrCat_24C3810 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24C38A8 := THIStrCat.Create;
  with StrCat_24C38A8 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_464A950 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_464A950 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_464A9F0 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_464A9F0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Hub;
  Hub_253BA70 := THIHub.Create;
  with Hub_253BA70 do begin
    _prop_InCount := 1;
    _prop_OutCount := 2;
  end;
//Init for Hub;
  Hub_253BB20 := THIHub.Create;
  with Hub_253BB20 do begin
    _prop_InCount := 1;
    _prop_OutCount := 2;
  end;
//Init for StrCat;
  StrCat_24C39D8 := THIStrCat.Create;
  with StrCat_24C39D8 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Edit;
  Edit_464AA90 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_464AA90 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C3B08 := THIStrCat.Create;
  with StrCat_24C3B08 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Label;
  Label_464AB30 := THILabel.Create(Panel_24CD050.Control);
  with Label_464AB30 do begin
    ManFlags := 0;
    _prop_Left := 216;
    _prop_Top := 70;
    _prop_Width := 20;
    _prop_Height := 24;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',12,1,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Transparent := False;
    _prop_Caption := PChar('or'#0);
    _prop_AutoSize := True;
    _prop_Alignment := taLeft;
    _prop_ColorHover := 0;
    _prop_Underline := False;
    Init;
  end;
//Init for Label;
  Label_464ABD0 := THILabel.Create(Panel_24CD050.Control);
  with Label_464ABD0 do begin
    ManFlags := 0;
    _prop_Left := 216;
    _prop_Top := 95;
    _prop_Width := 20;
    _prop_Height := 24;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',12,1,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Transparent := False;
    _prop_Caption := PChar('or'#0);
    _prop_AutoSize := True;
    _prop_Alignment := taLeft;
    _prop_ColorHover := 0;
    _prop_Underline := False;
    Init;
  end;
//Init for Label;
  Label_464AC70 := THILabel.Create(Panel_24CD050.Control);
  with Label_464AC70 do begin
    ManFlags := 0;
    _prop_Left := 290;
    _prop_Top := 75;
    _prop_Width := 16;
    _prop_Height := 41;
    _prop_Align := caNone;
    _prop_Color := -16777201;
    _prop_Font := hiCreateFont('MS Sans Serif',26,1,0,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 1;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Transparent := False;
    _prop_Caption := PChar('}'#0);
    _prop_AutoSize := True;
    _prop_Alignment := taLeft;
    _prop_ColorHover := 0;
    _prop_Underline := False;
    Init;
  end;
//Init for Edit;
  Edit_464AD10 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_464AD10 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_464ADB0 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_464ADB0 do begin
    ManFlags := 0;
    _prop_Left := 675;
    _prop_Top := 205;
    _prop_Width := 55;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for StrCat;
  StrCat_24C3CD0 := THIStrCat.Create;
  with StrCat_24C3CD0 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for StrCat;
  StrCat_24C3E00 := THIStrCat.Create;
  with StrCat_24C3E00 do begin
    _prop_Str1 := PChar(#0);
    _prop_Str2 := PChar(#0);
  end;
//Init for Timer;
  Timer_24C3F30 := THITimer.Create;
  with Timer_24C3F30 do begin
    _prop_Interval := 3000;
    _prop_Enable := False;
    _prop_AutoStop := 1;
    _prop_OverCall := 0;
  end;
//Init for Edit;
  Edit_464AE50 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_464AE50 do begin
    ManFlags := 0;
    _prop_Left := 1315;
    _prop_Top := 370;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',8,0,0,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(' '#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_464AEF0 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_464AEF0 do begin
    ManFlags := 0;
    _prop_Left := 1285;
    _prop_Top := 305;
    _prop_Width := 50;
    _prop_Height := 20;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',10,0,255,1);
    _prop_ParentFont := False;
    _prop_Visible := False;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar('Код скопирован в буфер обмена!'#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := False;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
//Init for Edit;
  Edit_464AF90 := THIEdit.Create(Panel_24CD050.Control);
  with Edit_464AF90 do begin
    ManFlags := 0;
    _prop_Left := 475;
    _prop_Top := 50;
    _prop_Width := 260;
    _prop_Height := 25;
    _prop_Align := caNone;
    _prop_Color := -16777211;
    _prop_Font := hiCreateFont('MS Sans Serif',10,1,255,1);
    _prop_ParentFont := False;
    _prop_Visible := True;
    _prop_Enabled := True;
    _prop_Cursor := crDefault;
    _prop_TabOrder := 0;
    _prop_Ctl3D := 0;
    _prop_WinStyle := 0;
    _prop_Name := PChar(#0);
    _prop_Hint := PChar(#0);
    _prop_WidthScale := 0;
    _prop_HeightScale := 0;
    _prop_ModeSp := spNone;
    _prop_SizeSp := 4;
    _prop_ColorSp := -16777201;
    _prop_MinOwn := 0;
    _prop_MinRest := 0;
    _prop_Text := PChar(#0);
    _prop_Alignment := 0;
    _prop_DataType := Text;
    _prop_Password := False;
    _prop_ReadOnly := True;
    _prop_MaxLenField := 0;
    _prop_ClearAfterEnter := True;
    Init;
  end;
  Child := EditMulti_245D050;
  EditMulti_245D050.MainClass := Self;
  EditMulti_245D050.Parent := _parent;
 //Make all connection in scheme
  EditMulti_245D050.Works[0]               := _DoEvent(Panel_24CD050._work_doVisible,1);
  Edit_24CD730._event_onChange             := _DoEvent(Edit_464A950._work_doText,0);
  Edit_24CD870._event_onChange             := _DoEvent(Edit_4649910._work_doText,0);
  StrCat_24C0AF0._event_onStrCat           := _DoEvent(Edit_24CD4B0._work_doText,0);
  StrCat_24C0AF0._data_Str1                := _DoEvent(Edit_24CD0F0._var_Text,0);
  Button_24CD7D0._event_onClick            := _DoEvent(Edit_24CD730._work_doText,0);
  Button_24CD550._event_onClick            := _DoEvent(StrCat_24C0CB8._work_doStrCat,0);
  Edit_24CD0F0._event_onChange             := _DoEvent(Edit_24CD4B0._work_doText,0);
  StrCat_24C0CB8._event_onStrCat           := _DoEvent(Edit_4649550._work_doText,0);
  StrCat_24C0CB8._data_Str1                := _DoEvent(Edit_24CD4B0._var_Text,0);
  Edit_24CD4B0._event_onChange             := _DoEvent(Edit_4649550._work_doText,0);
  Button_4649410._event_onClick            := _DoEvent(StrCat_24C0C20._work_doStrCat,0);
  StrCat_24C0C20._event_onStrCat           := _DoEvent(Edit_24CD870._work_doText,0);
  StrCat_24C0C20._data_Str1                := _DoEvent(Edit_4649550._var_Text,0);
  Edit_4649550._event_onChange             := _DoEvent(Edit_24CD870._work_doText,0);
  Button_4649370._event_onClick            := _DoEvent(StrCat_24C0AF0._work_doStrCat,0);
  Button_4649730._event_onClick            := _DoEvent(StrCat_24C2B00._work_doStrCat,0);
  Button_46497D0._event_onClick            := _DoEvent(StrCat_24C2B98._work_doStrCat,0);
  Button_4649870._event_onClick            := _DoEvent(StrCat_24C2C30._work_doStrCat,0);
  Edit_4649910._event_onChange             := _DoEvent(Edit_4649A50._work_doText,0);
  StrCat_24C2B00._event_onStrCat           := _DoEvent(Edit_4649910._work_doText,0);
  StrCat_24C2B00._data_Str1                := _DoEvent(Edit_24CD870._var_Text,0);
  StrCat_24C2B98._event_onStrCat           := _DoEvent(Edit_4649A50._work_doText,0);
  StrCat_24C2B98._data_Str1                := _DoEvent(Edit_4649910._var_Text,0);
  StrCat_24C2C30._event_onStrCat           := _DoEvent(Edit_4649FF0._work_doText,0);
  StrCat_24C2C30._data_Str1                := _DoEvent(Edit_4649A50._var_Text,0);
  Edit_4649A50._event_onChange             := _DoEvent(Edit_4649FF0._work_doText,0);
  ClipboardHook_24C2CC8._data_Text         := _DoEvent(Edit_46499B0._var_Text,0);
  Edit_4649AF0._event_onChange             := _DoEvent(Edit_4649C30._work_doText,0);
  ComboBox_4649B90._event_onClick          := _DoEvent(StrCat_24C2D60._work_doStrCat,0);
  StrCat_24C2D60._event_onStrCat           := _DoEvent(Edit_46494B0._work_doText,0);
  StrCat_24C2D60._data_Str1                := _DoEvent(Edit_464A3B0._var_Text,0);
  Edit_4649C30._event_onChange             := _DoEvent(Edit_4649690._work_doText,0);
  Button_4649D70._event_onClick            := _DoEvent(StrCat_24C3188._work_doStrCat,0);
  Button_4649EB0._event_onClick            := _DoEvent(StrCat_24C2DF8._work_doStrCat,0);
  Button_4649F50._event_onClick            := _DoEvent(Hub_253B910.doEvent,0);
  StrCat_24C2DF8._event_onStrCat           := _DoEvent(Edit_4649C30._work_doText,0);
  StrCat_24C2DF8._data_Str1                := _DoEvent(Edit_4649AF0._var_Text,0);
  StrCat_24C2DF8._data_Str2                := _DoEvent(Edit_4649CD0._var_Text,0);
  StrCat_24C2F28._event_onStrCat           := _DoEvent(Edit_4649690._work_doText,0);
  StrCat_24C2F28._data_Str1                := _DoEvent(Edit_4649C30._var_Text,0);
  Edit_4649690._event_onChange             := _DoEvent(Edit_464A3B0._work_doText,0);
  Edit_46495F0._event_onChange             := _DoEvent(Edit_46499B0._work_doText,0);
  Edit_46494B0._event_onChange             := _DoEvent(Edit_46495F0._work_doText,0);
  StrCat_24C3058._event_onStrCat           := _DoEvent(Edit_464A3B0._work_doText,0);
  StrCat_24C3058._data_Str1                := _DoEvent(Edit_4649690._var_Text,0);
  StrCat_24C3058._data_Str2                := _DoEvent(Edit_4649E10._var_Text,0);
  Hub_253B910.onEvent[0]                   := _DoEvent(StrCat_24C2F28._work_doStrCat,0);
  Hub_253B910.onEvent[1]                   := _DoEvent(StrCat_24C3058._work_doStrCat,0);
  Edit_4649FF0._event_onChange             := _DoEvent(Edit_4649AF0._work_doText,0);
  StrCat_24C3188._event_onStrCat           := _DoEvent(Edit_4649AF0._work_doText,0);
  StrCat_24C3188._data_Str1                := _DoEvent(Edit_4649FF0._var_Text,0);
  Button_464A310._event_onClick            := _DoEvent(Hub_2538B00.doEvent,0);
  StrCat_24C32B8._event_onStrCat           := _DoEvent(Edit_46495F0._work_doText,0);
  StrCat_24C32B8._data_Str1                := _DoEvent(Edit_46494B0._var_Text,0);
  Hub_2538B00.onEvent[0]                   := _DoEvent(StrCat_24C32B8._work_doStrCat,0);
  Hub_2538B00.onEvent[1]                   := _DoEvent(StrCat_24C3350._work_doStrCat,0);
  StrCat_24C3350._event_onStrCat           := _DoEvent(Edit_46499B0._work_doText,0);
  StrCat_24C3350._data_Str1                := _DoEvent(Edit_46495F0._var_Text,0);
  StrCat_24C3350._data_Str2                := _DoEvent(Edit_464A270._var_Text,0);
  Edit_464A3B0._event_onChange             := _DoEvent(Edit_46494B0._work_doText,0);
  Button_464A450._event_onClick            := _DoEvent(Hub_253B9C0.doEvent,0);
  Hub_253B9C0.onEvent[0]                   := _DoEvent(ClipboardHook_24C2CC8._work_doSetText,0);
  Hub_253B9C0.onEvent[1]                   := _DoEvent(Edit_464AEF0._work_doText,0);
  Button_464A4F0._event_onClick            := _DoEvent(Hub_253BA70.doEvent,0);
  Button_464A590._event_onClick            := _DoEvent(Hub_253BB20.doEvent,0);
  Button_464A630._event_onClick            := _DoEvent(StrCat_24C3CD0._work_doStrCat,0);
  Button_464A6D0._event_onClick            := _DoEvent(StrCat_24C3E00._work_doStrCat,0);
  StrCat_24C3810._event_onStrCat           := _DoEvent(Edit_464AD10._work_doText,0);
  StrCat_24C3810._data_Str1                := _DoEvent(Edit_464A950._var_Text,0);
  StrCat_24C3810._data_Str2                := _DoEvent(Edit_464A8B0._var_Text,0);
  StrCat_24C38A8._event_onStrCat           := _DoEvent(Edit_464A950._work_doText,0);
  StrCat_24C38A8._data_Str1                := _DoEvent(Edit_24CD730._var_Text,0);
  Edit_464A950._event_onChange             := _DoEvent(Edit_464AD10._work_doText,0);
  Edit_464A9F0._event_onChange             := _DoEvent(Edit_464AA90._work_doText,0);
  Hub_253BA70.onEvent[0]                   := _DoEvent(StrCat_24C38A8._work_doStrCat,0);
  Hub_253BA70.onEvent[1]                   := _DoEvent(StrCat_24C3810._work_doStrCat,0);
  Hub_253BB20.onEvent[0]                   := _DoEvent(StrCat_24C39D8._work_doStrCat,0);
  Hub_253BB20.onEvent[1]                   := _DoEvent(StrCat_24C3B08._work_doStrCat,0);
  StrCat_24C39D8._event_onStrCat           := _DoEvent(Edit_464AA90._work_doText,0);
  StrCat_24C39D8._data_Str1                := _DoEvent(Edit_464A9F0._var_Text,0);
  Edit_464AA90._event_onChange             := _DoEvent(Edit_24CD0F0._work_doText,0);
  StrCat_24C3B08._event_onStrCat           := _DoEvent(Edit_24CD0F0._work_doText,0);
  StrCat_24C3B08._data_Str1                := _DoEvent(Edit_464AA90._var_Text,0);
  StrCat_24C3B08._data_Str2                := _DoEvent(Edit_464A810._var_Text,0);
  Edit_464AD10._event_onChange             := _DoEvent(Edit_464ADB0._work_doText,0);
  Edit_464ADB0._event_onChange             := _DoEvent(Edit_464A9F0._work_doText,0);
  StrCat_24C3CD0._event_onStrCat           := _DoEvent(Edit_464ADB0._work_doText,0);
  StrCat_24C3CD0._data_Str1                := _DoEvent(Edit_464AD10._var_Text,0);
  StrCat_24C3E00._event_onStrCat           := _DoEvent(Edit_464A9F0._work_doText,0);
  StrCat_24C3E00._data_Str1                := _DoEvent(Edit_464ADB0._var_Text,0);
  Timer_24C3F30._event_onTimer             := _DoEvent(Edit_464AE50._work_doText,0);
  Edit_464AE50._event_onChange             := _DoEvent(Edit_464AF90._work_doText,0);
  Edit_464AEF0._event_onChange             := _DoEvent(Edit_464AF90._work_doText,0);
  Edit_464AF90._event_onChange             := _DoEvent(Timer_24C3F30._work_doTimer,0);
  Panel_24CD050._prop_HintManager := nil;
  Panel_24CD050._prop_Layout := nil;
  Edit_24CD730._prop_HintManager := nil;
  Edit_24CD730._prop_Layout := nil;
  Edit_24CD870._prop_HintManager := nil;
  Edit_24CD870._prop_Layout := nil;
  Button_24CD7D0._prop_HintManager := nil;
  Button_24CD7D0._prop_Layout := nil;
  Button_24CD550._prop_HintManager := nil;
  Button_24CD550._prop_Layout := nil;
  Edit_24CD0F0._prop_HintManager := nil;
  Edit_24CD0F0._prop_Layout := nil;
  Edit_24CD4B0._prop_HintManager := nil;
  Edit_24CD4B0._prop_Layout := nil;
  Button_4649410._prop_HintManager := nil;
  Button_4649410._prop_Layout := nil;
  Edit_4649550._prop_HintManager := nil;
  Edit_4649550._prop_Layout := nil;
  Button_4649370._prop_HintManager := nil;
  Button_4649370._prop_Layout := nil;
  Button_4649730._prop_HintManager := nil;
  Button_4649730._prop_Layout := nil;
  Button_46497D0._prop_HintManager := nil;
  Button_46497D0._prop_Layout := nil;
  Button_4649870._prop_HintManager := nil;
  Button_4649870._prop_Layout := nil;
  Edit_4649910._prop_HintManager := nil;
  Edit_4649910._prop_Layout := nil;
  Edit_46499B0._prop_HintManager := nil;
  Edit_46499B0._prop_Layout := nil;
  Edit_4649A50._prop_HintManager := nil;
  Edit_4649A50._prop_Layout := nil;
  Edit_4649AF0._prop_HintManager := nil;
  Edit_4649AF0._prop_Layout := nil;
  ComboBox_4649B90._prop_HintManager := nil;
  ComboBox_4649B90._prop_Layout := nil;
  ComboBox_4649B90._prop_IndexManager := nil;
  ComboBox_4649B90._prop_BoxDrawManager := nil;
  ComboBox_4649B90._prop_IconsManager := nil;
  Edit_4649C30._prop_HintManager := nil;
  Edit_4649C30._prop_Layout := nil;
  Edit_4649CD0._prop_HintManager := nil;
  Edit_4649CD0._prop_Layout := nil;
  Button_4649D70._prop_HintManager := nil;
  Button_4649D70._prop_Layout := nil;
  Edit_4649E10._prop_HintManager := nil;
  Edit_4649E10._prop_Layout := nil;
  Button_4649EB0._prop_HintManager := nil;
  Button_4649EB0._prop_Layout := nil;
  Button_4649F50._prop_HintManager := nil;
  Button_4649F50._prop_Layout := nil;
  Edit_4649690._prop_HintManager := nil;
  Edit_4649690._prop_Layout := nil;
  Edit_46495F0._prop_HintManager := nil;
  Edit_46495F0._prop_Layout := nil;
  Edit_46494B0._prop_HintManager := nil;
  Edit_46494B0._prop_Layout := nil;
  Edit_4649FF0._prop_HintManager := nil;
  Edit_4649FF0._prop_Layout := nil;
  Label_464A090._prop_HintManager := nil;
  Label_464A090._prop_Layout := nil;
  Label_464A130._prop_HintManager := nil;
  Label_464A130._prop_Layout := nil;
  Label_464A1D0._prop_HintManager := nil;
  Label_464A1D0._prop_Layout := nil;
  Edit_464A270._prop_HintManager := nil;
  Edit_464A270._prop_Layout := nil;
  Button_464A310._prop_HintManager := nil;
  Button_464A310._prop_Layout := nil;
  Edit_464A3B0._prop_HintManager := nil;
  Edit_464A3B0._prop_Layout := nil;
  Button_464A450._prop_HintManager := nil;
  Button_464A450._prop_Layout := nil;
  Button_464A4F0._prop_HintManager := nil;
  Button_464A4F0._prop_Layout := nil;
  Button_464A590._prop_HintManager := nil;
  Button_464A590._prop_Layout := nil;
  Button_464A630._prop_HintManager := nil;
  Button_464A630._prop_Layout := nil;
  Button_464A6D0._prop_HintManager := nil;
  Button_464A6D0._prop_Layout := nil;
  Label_464A770._prop_HintManager := nil;
  Label_464A770._prop_Layout := nil;
  Edit_464A810._prop_HintManager := nil;
  Edit_464A810._prop_Layout := nil;
  Edit_464A8B0._prop_HintManager := nil;
  Edit_464A8B0._prop_Layout := nil;
  Edit_464A950._prop_HintManager := nil;
  Edit_464A950._prop_Layout := nil;
  Edit_464A9F0._prop_HintManager := nil;
  Edit_464A9F0._prop_Layout := nil;
  Edit_464AA90._prop_HintManager := nil;
  Edit_464AA90._prop_Layout := nil;
  Label_464AB30._prop_HintManager := nil;
  Label_464AB30._prop_Layout := nil;
  Label_464ABD0._prop_HintManager := nil;
  Label_464ABD0._prop_Layout := nil;
  Label_464AC70._prop_HintManager := nil;
  Label_464AC70._prop_Layout := nil;
  Edit_464AD10._prop_HintManager := nil;
  Edit_464AD10._prop_Layout := nil;
  Edit_464ADB0._prop_HintManager := nil;
  Edit_464ADB0._prop_Layout := nil;
  Edit_464AE50._prop_HintManager := nil;
  Edit_464AE50._prop_Layout := nil;
  Edit_464AEF0._prop_HintManager := nil;
  Edit_464AEF0._prop_Layout := nil;
  Edit_464AF90._prop_HintManager := nil;
  Edit_464AF90._prop_Layout := nil;
  Panel_24CD050.Control.Tabulate;

  ParentElement := Panel_24CD050;
end;

destructor TClassChildPanel_2538A50.Destroy;
begin
  Edit_464AF90.Destroy;
  Edit_464AEF0.Destroy;
  Edit_464AE50.Destroy;
  Timer_24C3F30.Destroy;
  StrCat_24C3E00.Destroy;
  StrCat_24C3CD0.Destroy;
  Edit_464ADB0.Destroy;
  Edit_464AD10.Destroy;
  Label_464AC70.Destroy;
  Label_464ABD0.Destroy;
  Label_464AB30.Destroy;
  StrCat_24C3B08.Destroy;
  Edit_464AA90.Destroy;
  StrCat_24C39D8.Destroy;
  Hub_253BB20.Destroy;
  Hub_253BA70.Destroy;
  Edit_464A9F0.Destroy;
  Edit_464A950.Destroy;
  StrCat_24C38A8.Destroy;
  StrCat_24C3810.Destroy;
  Edit_464A8B0.Destroy;
  Edit_464A810.Destroy;
  Label_464A770.Destroy;
  Button_464A6D0.Destroy;
  Button_464A630.Destroy;
  Button_464A590.Destroy;
  Button_464A4F0.Destroy;
  Hub_253B9C0.Destroy;
  Button_464A450.Destroy;
  Edit_464A3B0.Destroy;
  StrCat_24C3350.Destroy;
  Hub_2538B00.Destroy;
  StrCat_24C32B8.Destroy;
  Button_464A310.Destroy;
  Edit_464A270.Destroy;
  Label_464A1D0.Destroy;
  Label_464A130.Destroy;
  Label_464A090.Destroy;
  StrCat_24C3188.Destroy;
  Edit_4649FF0.Destroy;
  Hub_253B910.Destroy;
  StrCat_24C3058.Destroy;
  Edit_46494B0.Destroy;
  Edit_46495F0.Destroy;
  Edit_4649690.Destroy;
  StrCat_24C2F28.Destroy;
  StrCat_24C2DF8.Destroy;
  Button_4649F50.Destroy;
  Button_4649EB0.Destroy;
  Edit_4649E10.Destroy;
  Button_4649D70.Destroy;
  Edit_4649CD0.Destroy;
  Edit_4649C30.Destroy;
  StrCat_24C2D60.Destroy;
  ComboBox_4649B90.Destroy;
  Edit_4649AF0.Destroy;
  ClipboardHook_24C2CC8.Destroy;
  Edit_4649A50.Destroy;
  Edit_46499B0.Destroy;
  StrCat_24C2C30.Destroy;
  StrCat_24C2B98.Destroy;
  StrCat_24C2B00.Destroy;
  Edit_4649910.Destroy;
  Button_4649870.Destroy;
  Button_46497D0.Destroy;
  Button_4649730.Destroy;
  Button_4649370.Destroy;
  Edit_4649550.Destroy;
  StrCat_24C0C20.Destroy;
  Button_4649410.Destroy;
  Edit_24CD4B0.Destroy;
  StrCat_24C0CB8.Destroy;
  Edit_24CD0F0.Destroy;
  Button_24CD550.Destroy;
  Button_24CD7D0.Destroy;
  StrCat_24C0AF0.Destroy;
  Edit_24CD870.Destroy;
  Edit_24CD730.Destroy;
  EditMulti_245D050.Destroy;
  Panel_24CD050.Destroy;
  inherited;
end;


end.
